### ISSUE TITLE
Highlight color for results separator

### ISSUE THREAD

**Issue by ratheesh** [gelguy/wilder.nvim#1]
This is a great plugin and more improved compared to Cmd2.

Can you let me know how to customize highlighting for the separator between results? Example would be great.

**Comment by gelguy** [comment]
Thanks for using the plugin!

I've added `separator_hl` to the renderer options.
```vim
call wilder#set_option('renderer', wilder#statusline_renderer({
      \ 'separator_hl': 'MySeparatorHighlight',
      \ }))
```
