### ISSUE TITLE
incsearch flickering in Neovim nightly

### ISSUE THREAD

**Issue by Gelio** [gelguy/wilder.nvim#105]
Hey! I've been using this plugin and it's been working great for me so far after https://github.com/gelguy/wilder.nvim/issues/30 was fixed.

Lately, I've noticed that the problem came back. I haven't changed anything in my wilder.nvim config when it surfaced.

I am using neovim nightly:

```sh
$ nvim -v
NVIM v0.6.0-dev+493-g035d82e0d
```

My config: https://github.com/Gelio/ubuntu-dotfiles/blob/d38eb8c8b176e6f7287e19a520f49bcb429b64b1/install/neovim/stowed/.config/nvim/wilder.vim

I am using `wildmenu_renderer` for `/` and `?`.

I am afraid it might be related to https://github.com/gelguy/wilder.nvim/commit/28b26ffa8c3a8bdc34e00bc971199d1bfba30c8f. After adding 

```viml
    \   'apply_incsearch_fix': v:true,
```

in the config for `wildmenu_renderer` (see commit https://github.com/Gelio/ubuntu-dotfiles/commit/cf03f95a482ce2b5bda9b5f70eb8e822c025fba1), the flickering is gone.

**Comment by gelguy** [comment]
Thanks for using the plugin!

From the provided config I see you're using `nvim-scrollview`. This causes issues with the incsearch highlighting when used in combination with `wilder`. See https://github.com/gelguy/wilder.nvim/issues/30#issuecomment-891982912 for more details and a workaround.

The tradeoff of `apply_incsearch_fix` is that it breaks scrolling through the `/` history with `<Up>` and `<Down>`. If you're okay with that then you can just use `apply_incsearch_fix` and skip the workaround.

**Comment by Gelio** [comment]
I see, thanks for the explanation. I didn't know nvim-scrollview had anything to do with it (even though I participated in that issue, funnily enough).

> The tradeoff of apply_incsearch_fix is that it breaks scrolling through the / history with <Up> and <Down>. If you're okay with that then you can just use apply_incsearch_fix and skip the workaround.

`<C-n>` and `<C-p>` are consistently working for me and are a primary way of scrolling through `/` results.

If everything is working as expected and https://github.com/gelguy/wilder.nvim/commit/28b26ffa8c3a8bdc34e00bc971199d1bfba30c8f was not made by mistake, I'll close the issue.

One thing I believe may be worth it is documenting the `apply_incsearch_fix` fix (and the fact that it is not automatically set on neovim 0.6)

**Comment by gelguy** [comment]
Just to clarify: `/` history is broken entirely, so `<C-n>` and `<C-p>` will not work too.

For the `apply_incsearch_fix` flag, the default is intended to be `0` since it breaks the `/` history. It is meant as a workaround for the incsearch highlighting bug that occurs in Nvim 0.5 and other cases.

**Comment by Gelio** [comment]
> Just to clarify: `/` history is broken entirely, so `<C-n>` and `<C-p>` will not work too.

I just want to say that `<C-n>` and `<C-p>` are working pretty well for me with `apply_incsearch_fix`, though

https://user-images.githubusercontent.com/889383/139591369-d6e73fa8-4be2-4e11-bf16-427db9524847.mp4

`<Up>` and `<Down>` are broken, this is right, but I didn't notice anything being broken about `<C-n>` and `<C-p>`, just saying
