### ISSUE TITLE
tab completion on cmdline after string doesn't complete folder path

### ISSUE THREAD

**Issue by timtyrrell** [gelguy/wilder.nvim#106]
Sorry if the title is unclear, here are the examples with the minimal config below. Not sure if a bug of a misconfiguration on my part. Amazing plugin ❤️ 

_without wilder_
`:vimgrep "test" <TAB>` brings up a folder picker

_with wilder_
`:vimgrep "test" <TAB>` does nothing

```
set nocompatible
filetype plugin indent on
syntax on
set hidden

call plug#begin('~/.config/nvim/plugged')
Plug 'gelguy/wilder.nvim'
call plug#end()

call wilder#enable_cmdline_enter()
set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : '\<Tab>'
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : '\<S-Tab>'

call wilder#set_option('modes', ['/', '?', ':'])
```

**Comment by gelguy** [comment]
Thanks for the report! I can reproduce this.

Looks like there's an error in parsing the command - everything past the first `"` is treated as a comment. I'll be working on a fix.

**Comment by gelguy** [comment]
Apologies for the delay!

I've pushed 17fdd372997fe79774a7179fe1570940c6371de6 which should fix this issue. Could you help verify by pulling the latest `master` branch?

**Comment by timtyrrell** [comment]
@gelguy Tested it out, looks good to me 👍 Trying with `:FZF` also and good.
