### ISSUE TITLE
Completion issues when there are spaces in paths

### ISSUE THREAD

**Issue by jaekyeom** [gelguy/wilder.nvim#118]
It looks that wilder.nvim doesn't work correctly when there exist spaces in paths.

https://user-images.githubusercontent.com/6262727/148670695-04676c84-1564-44e9-a169-b91ce56e6fad.mov

I'm using `'language': 'python'` and `'fuzzy': 1` for `wilder#cmdline_pipeline`.

Can this be fixed by updating my configs, or does it require some updates to the plugin?

Thank you.

**Comment by gelguy** [comment]
Thanks for the report and recording! I can reproduce this.

Could you help check if f50d79a3f9ef07be3c0c8a0f49faaeea803a8c0c fixes this issue for you by pulling the latest `master`?

**Comment by jaekyeom** [comment]
Wow, I think it now works well without issues.
Thank you so much for the quick patch!
