### ISSUE TITLE
pipeline: Vim(call):E117: unknown function: _wilder_python_search

### ISSUE THREAD

**Issue by torish14** [gelguy/wilder.nvim#119]
I get a title error when using the wild menu.

Using the `:CheckHealth` command hasn't caused any errors in python.

![スクリーンショット 0004-01-17 6 36 39](https://user-images.githubusercontent.com/49876561/149679024-e33260ce-8ba5-437d-95ef-4535b9832877.png)

Below is the setting of wilder.nvim

![スクリーンショット 0004-01-17 6 38 19](https://user-images.githubusercontent.com/49876561/149679133-f5cd0d55-5798-414b-99e6-6a55f0a7bfc7.png)

Are there any other possible causes?

**Comment by gelguy** [comment]
There's a warning for the Python3 provider: `No python executable found that can import neovim`. Could you help check if `:python3 import neovim` gives no errors for you?

Otherwise could you try `:UpdateRemotePlugins` and checking if the output message contains `wilder` (it should look something like `remote/host: python3 host registered plugins ['wilder']`)?

**Comment by torish14** [comment]
Thank you for your quick response!

I have no error in `:python3 import neovim` command.

But in `:UpdateRemotePlugins` command, have an error that `E492 not an editor: UpdateRemotePlugins`

**Comment by gelguy** [comment]
That's strange since `UpdateRemotePlugins` is part of Neovim's default runtime scripts.

Could you paste the output of `:filter remote scriptnames` and `verbose command UpdateRemotePlugins`?

Otherwise I would need more information about your config e.g. minimal vimrc to reproduce the issue, Neovim `:version`.

**Comment by torish14** [comment]
In `:filter remote scriptnames` command, output below.

![スクリーンショット 0004-01-18 9 23 58](https://user-images.githubusercontent.com/49876561/149850720-93c2e315-b294-4820-ab97-9ff35de317ee.png)

And in `:verbose command UpdateRemotePlugins` command, has an error that `User defined command not found`.

**Comment by gelguy** [comment]
Could you try `:runtime! plugin/rplugin.vim` and then `:UpdateRemotePlugins`?

If this still doesn't work then I think your runtime files aren't correctly set up.

**Comment by torish14** [comment]
I tried that but didn't work.

Should I rebuild neovim from the beginning?

**Comment by gelguy** [comment]
Could you run Neovim with `nvim- u NONE` and the try `:UpdateRemotePlugins`?

If that doesn't work then your runtime files aren't properly configured - check `:echo $VIMRUNTIME` and see if it points to the correct runtime directory.

**Comment by torish14** [comment]
I did `nvim -u NONE` and `:UpdateRemotePlugins` but didn't work.

However it works fine that run `nvim -u NORC` and `:UpdateRemotePlugins`.

Also did `:echo $VIMRUNTIME` return the path `/usr/local/Cellar/neovim/0.6.1/share/nvim/runtime`.

※As a side note, my machine is macOS Big Sur 11.6.2, `:echo $VIM` return the path `/usr/local/Cellar/neovim/0.6.1/share/nvim`

**Comment by gelguy** [comment]
My bad, I meant `nvim -u NORC` in my original post.

This means there's something in your `init.vim` interfering with the loading of `rplugin.vim`. Will you be able to provide your full `init.vim` config?

**Comment by torish14** [comment]
Well, I'm glad I wrote that, just in case.

Of course.
[init.vim in my dotfiles](https://github.com/torish14/dotfiles/blob/main/.config/nvim/init.vim)

Please check🙏

**Comment by gelguy** [comment]
This line causes the issue: 
https://github.com/torish14/dotfiles/blob/89fd0d4ae797ab1e71a92ded2ff0ed8db13aa1d8/.config/nvim/init.vim#L238

```
let g:loaded_remote_plugins     = 1
```
This skips the loading of the `rplugin.vim`  file.

**Comment by torish14** [comment]
My apologies.
I completely forgot that I had it set up this way for delayed loading💦

I'm sorry to have taken so long.

I was able to use `wilder.nvim` successfully🎉

Thanks a lot!!
