### ISSUE TITLE
're2' engine error: module 're2' has no attribute 'UNICODE'

### ISSUE THREAD

**Issue by goduck777** [gelguy/wilder.nvim#123]
When I use "re2" engine for python_search_pipeline, I got the following error
```
python_search: module 're2' has no attribute 'UNICODE'  
```
I have already installed pyre2 package in python.

**Comment by gelguy** [comment]
Could you provide the output of `pip show pyre2`?

When running `nvim -u NORC`, what's the output of `:python3 import re2` and `:python3 print(re2.UNICODE)`?
