### ISSUE TITLE
Need more helpful message than `python_file_finder: non-zero return code`

### ISSUE THREAD

**Issue by wookayin** [gelguy/wilder.nvim#126]
In some environments where the internal command line programs are not available, I see some error message like `python_filer_finder: non-zero return code 1` but it doesn't tell what exactly is wrong. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1009873/160499659-f5332272-dc37-41e0-94f0-ce38d4b8dbe0.png">

Request: It would be nice if the full command line was shown so that users can easily figure out which command has failed.

## Some details that has nothing to do with wilder.nvim itself:

Relevant config of mine:

```
let l:pipeline.file_fuzzy = executable('fd') && has('nvim-0.5.0') ?                                 
┊ ┊ ┊ \ wilder#python_file_finder_pipeline({                                                        
┊ ┊ ┊ \   'debounce': 50,                                                                           
┊ ┊ ┊ \   'file_command': {ctx, arg -> v:lua._wilder_fuzzy_fd_pipeline_command(ctx, arg, 'f')},     
┊ ┊ ┊ \   'dir_command':  {ctx, arg -> v:lua._wilder_fuzzy_fd_pipeline_command(ctx, arg, 'd')},     
┊ ┊ ┊ \   'filters': ['fuzzy_filter', 'difflib_sorter'],                                            
┊ ┊ ┊ \   'path': {-> getcwd()},                                                                    
┊ ┊ ┊ \ }) : l:pipeline.noop                                                                        
```

For me, the custom function `v:lua._wilder_fuzzy_fd_pipeline_command` were resolving the command to `fd --type f --type d . --maxdepth 5`, but unfortunately `--maxdepth` option was not available (requires fd v8.0+).

**Comment by gelguy** [comment]
Thanks for reporting!

I've fixed this on the in-progress `palette` branch, commit 23a635a098c28164a993fa271082349add63f845 specifically. It's a small patch so you could patch it locally. Otherwise I can push this to `master` since I don't know when the `palette` branch will be merged.

**Comment by wookayin** [comment]
Glad to hear that you already implemented in the branch!  This works quite nice and I would be happy if you can cherry-pick the feature to the master branch.

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/1009873/160527990-fd105dc8-1db5-42c9-810e-abc9a8d08d8c.png">

One very minor nitpicking would be: you might also want to strip escape sequences (ANSI escape codes for foreground color, etc.), but having it as-is would be also fine. This is so helpful!

**Comment by gelguy** [comment]
I've merged this to `master` along with your suggestions on the ANSI escape codes and showing the command line string. Let me know if you have other suggestions regarding the error message. Thanks!

**Comment by wookayin** [comment]
Glad to hear that #127 is merged! Awesome, thanks! It looks perfect to me.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/1009873/161431577-557bba0f-e2f3-4669-be07-1ac6462412e5.png">

**Comment by hasufell** [comment]
![Screenshot_2024-10-04_16-00-01](https://github.com/user-attachments/assets/62494cff-de4b-4d2e-be52-884ec83d400c)

Still unhelpful messages. It doesn't even tell me which binary it choked on.
