### ISSUE TITLE
About `Wilder Float`

### ISSUE THREAD

**Issue by 0x00-ketsu** [gelguy/wilder.nvim#136]
Hey @gelguy is there has method to delete `Wilder Float` buffer after invoked wilder.nvim.
I'm using with neovim: v0.7.0
Thanks!

screenshot:
![s1](https://user-images.githubusercontent.com/16932133/168423161-7e26ac21-5f70-4680-9085-4ee41035f8a4.png)

**Comment by gelguy** [comment]
Can I check which `tabline` plugin you are using? The float opened by `wilder` is set to `hidden` and `unlisted`, so the tab bar shouldn't be including it.

**Comment by 0x00-ketsu** [comment]
My use tabline is `vim-airline`.
I recheck my neovim config file, found the cause, it's my mistake, I enabled `:silent e` when `BufEnter`.
