### ISSUE TITLE
[Question:] Cannot use python_search

### ISSUE THREAD

**Issue by OliverChao** [gelguy/wilder.nvim#137]
![Screenshot from 2022-05-22 10-27-58](https://user-images.githubusercontent.com/39361033/169675696-f45b1c4d-79d9-4c8b-8bed-83f09fe945a7.png)

I don't konw why nvim fails to find the function **_wilder_python_file_finder**.
And, my wilder option is :
```
" ========= wilder command bar settings ==========
" Default keys
call wilder#setup({'modes': [':', '/', '?']})

call wilder#set_option('pipeline', [
	  \   wilder#branch(
	  \     wilder#python_file_finder_pipeline({
	  \       'file_command': ['rg', '--files'],
	  \       'dir_command': ['find', '.', '-type', 'd', '-printf', '%P\n'],
	  \       'filters': ['fuzzy_filter', 'difflib_sorter'],
	  \     }),
	  \     wilder#cmdline_pipeline(),
	  \     wilder#python_search_pipeline(),
	  \   ),
	  \ ])
call wilder#set_option('renderer', wilder#popupmenu_renderer(wilder#popupmenu_border_theme({
			\ 'border': 'rounded',
			\ 'highlighter': wilder#basic_highlighter(),
			  \ 'min_width': '15%',
			  \ 'min_height': '1%',
			\ 'highlights': {
				\   'border': 'Normal',
				\   'accent': wilder#make_hl('WilderAccent', 'Pmenu', [{}, {}, {'foreground': '#f4468f'}]),
				\ },
				\ 'left': [
					\   ' ', wilder#popupmenu_devicons(),
					\ ],
					\ 'right': [
						\   ' ', wilder#popupmenu_scrollbar(),
						\ ],
						\ })))

```

**Comment by gelguy** [comment]
Hi, are you using Vim or Neovim? Can you also paste the output for `:version`?

For Neovim, can you try running `:UpdateRemotePlugins` manually and see if it works?

For Vim, it's possible that `yarp` was not set up correctly, but I need more details from your setup.

**Comment by OliverChao** [comment]
Thanks!  I fix it up by running `:UpdateRemotePlugins`!.

I use the latest nvim, and the platform is Ubuntu 22.04.
![Screenshot from 2022-05-26 10-20-44](https://user-images.githubusercontent.com/39361033/170402767-a040ccb3-57ed-4c1e-b76f-75db0170a165.png)

After running `:UpdateRemotePlugins`,  I got the following message:
![Screenshot from 2022-05-26 10-24-06](https://user-images.githubusercontent.com/39361033/170403029-b2048b8a-6cfe-4869-837b-72eb049246c7.png)

And then, IT'S OK.
![Screenshot from 2022-05-26 10-29-24](https://user-images.githubusercontent.com/39361033/170403194-7d2a3893-de10-4b2d-863b-2ac5a3100b3b.png)
