### ISSUE TITLE
[Question] How to Use Faster Startup time with neovim?

### ISSUE THREAD

**Issue by wisnoskij** [gelguy/wilder.nvim#143]
When I use the code in [#faster-startup-time ](https://github.com/gelguy/wilder.nvim#faster-startup-time), I get the error on the first command line enter
`E55000: autocmd has thrown an exception Vim(call):E1117: Unknown function: <SNR>4_wilder#main#start`

At the end of my init.vim:
`autocmd CmdlineEnter * ++once call s:wilder_init() | call s:wilder#main#start()
function! s:wilder_init() abort
	call wilder#setup({
		\ 'modes': [':', '/', '?'],
		\ 'next_key': '<Tab>',
		\ 'previous_key': '<S-Tab>',
		\ 'accept_key': '<Down>',
		\ 'reject_key': '<Up>',
		\ })
endfunction`

**Comment by gelguy** [comment]
Thanks for the bug report! I made a mistake in the function name, it should be `wilder#main#start()` without the `s:`.

I've updated the README in 86f5fb0962bc5954babf267ded6b144d992aef85, could you help try again to see if it works?

**Comment by wisnoskij** [comment]
Thanks, That got rid of the error and the wilder menu still works.
