### ISSUE TITLE
Going up `command_palette` menu via `<c-k>` is broken

### ISSUE THREAD

**Issue by Danielhp95** [gelguy/wilder.nvim#147]
When using the `popupmenu_palette_theme` one should be able to use `<c-j>` to go down and `<c-k>` to go up. Going down is not a problem.

![image](https://user-images.githubusercontent.com/5859998/181052811-bef6a348-54dc-4e8a-a6c5-489b439d7a8f.png)

However, when going up via `<c-k>`, wilder seems to not accept it and instead it seems to take it as input to the vim command line itself.

![image](https://user-images.githubusercontent.com/5859998/181053016-577c5897-2a73-498e-a8e2-d41f921930b5.png)

Any idea on how to map `<c-k>` to go up?

In case that's useful, here's my `wilder` configuration that relates to `command_palette`:

```lua
local popupmenu_renderer = wilder.popupmenu_renderer(
  wilder.popupmenu_palette_theme({
    border = 'rounded',
    empty_message = wilder.popupmenu_empty_message_with_spinner(),
    highlighter = highlighters,
    left = {
      ' ',
      wilder.popupmenu_devicons(),
      wilder.popupmenu_buffer_flags({
        flags = ' a + ',
        icons = {['+'] = '', a = '', h = ''},
      }),
    },
    right = {
      ' ',
      wilder.popupmenu_scrollbar(),
    },
  })
)
```

Thank you a lot in advance!

**Comment by Ritzier** [comment]
Did u mean set the wilder keymappings?
Add these code in the wilder.setup function:
```
wilder.setup({
  next_key = "<C-j>",
  previous_key = "<C-k>",
})
```
You can check it in the readme page

**Comment by Danielhp95** [comment]
Yes, this was it, I missread the README. I apologize for the silly question then. Have a good day!
