### ISSUE TITLE
Clicking <CR> doesn't actually accept the task.

### ISSUE THREAD

**Issue by B4mbus** [gelguy/wilder.nvim#149]
When searching something an clicking enter the only thing happening is all the other items vanishing, the searched item is highlighted by clicking enter does nothing, I have to click `<Tab>` and then `<CR>` again to actually use the command.

Here's my config:
```lua
local wilder = require 'wilder'

wilder.setup {
	modes = {':', '/', '?'},
	next_key = '<Tab>',
	previous_key = '<S-Tab>',
	accept_key = '<Enter>',
	reject_key = '<Down>',
}

wilder.set_option('pipeline', {
	wilder.branch(
	wilder.cmdline_pipeline(),
	wilder.search_pipeline()
	),
})

wilder.set_option('renderer', wilder.wildmenu_renderer({
	highlighter = wilder.basic_highlighter(),
	separator = ' · ',
	left = {' ', wilder.wildmenu_spinner(), ' '},
	right = {' ', wilder.wildmenu_index()},
}))
```

Here's a gif:
![ooga2](https://user-images.githubusercontent.com/75364377/183223543-ec468f13-e9ce-48f7-8281-d1faa206b5d6.gif)

**Comment by gelguy** [comment]
Thanks for the report and the gif!

Can you check the output of `:verbose cmap` and find paste the entry for `<Enter>` here?

My suspicion is that you have to map it to `<CR>` and not `<Enter>`, i.e. `accept_key = '<CR>'`.

**Comment by B4mbus** [comment]
I did map it to `<CR>` and it's the same thing now. `verbose cmap` displays this:
![image](https://user-images.githubusercontent.com/75364377/183229492-b355142c-153d-4af6-bcc5-d8031422984e.png)

**Comment by gelguy** [comment]
Oh, `accept_key` here is referring to accepting the completion (see `:h wildmenu` under the `<Down>` special key).

The key to submit the commandline to be run is inherited from the default commandline, and so will be `<CR>` or `<CTRL-J>` (see `:h c_<CR>`). When `accept_key` is set to `<CR>`, it overrides the default key and so you aren't able to submit the commandline.

**Comment by B4mbus** [comment]
Makes sense, but does that mean the only way for me to do use `wildmenu` sensibly is to use `<C-<CR>>` or is is there anything I can do to make `<CR>` work?

**Comment by gelguy** [comment]
You can set it up to use the default `accept_key` and `reject_key`, e.g.
```vim
wilder.setup {
	modes = {':', '/', '?'},
	next_key = '<Tab>',
	previous_key = '<S-Tab>',
}
```
Then `<CR>` will submit the commandline.

Now that you've raised it up, the name `accept_key` is ambiguous and can probably be deprecated and renamed. I originally intended it to mean `accept` the current candidate (which replaces commandline with the new filename/menu and gets new candidates). I'll think of a better name and deprecate the old one.

**Comment by Dich0tomy** [comment]
@gelguy works, thanks.
