### ISSUE TITLE
Using external fuzzy finder

### ISSUE THREAD

**Issue by ratheesh** [gelguy/wilder.nvim#15]
In the present code, is there a provision to pass the completion through external tools like `fzf`?
If not, is there a plan to do this?
Currently, full fuzzy completion is not working for me.

**Comment by gelguy** [comment]
Hi, I can confirm fuzzy completion is not working for the completion pipeline.

I'm in the middle of a big refactoring which will fix this bug. You can find it in the `python_fuzzy_filter` branch. Note that there are breaking changes in the pipeline. The default components will work fine but if you have custom components, they might stop working.

Apologies for the bug, will merge the branch when its ready.

**Comment by ratheesh** [comment]
Hi, Thanks for your support.
I will look forward to the python fuzzy finder implementation.

**Comment by ratheesh** [comment]
@gelguy Just checking if you got a chance to look into fuzzy filter.
If it is easy, it would be nice to support third party fuzzy filters like fzf.

**Comment by gelguy** [comment]
I've pushed a major refactoring (#17) which fixes the fuzzy filtering issue. Fuzzy filtering should be working for the `cmdline_pipeline`.

```vim
wilder#cmdline_pipeline({
  'fuzzy': 1,
  'fuzzy_filter': wilder#python_fuzzy_filter(),
})
```

Regarding the use of external processes (e.g. `fzf`) for filtering, I don't have an easy way at the moment since some plumbing needs to be written to the pipeline to properly handle results from the process.

**Comment by ratheesh** [comment]
Thank you @gelguy for this.
Closing.

**Comment by tzachar** [comment]
Looks like most of the plumbing is implemented in [https://github.com/vijaymarupudi/nvim-fzf](vijaymarupudi/nvim-fzf)
Any chance of replacing the python code with fzf?

**Comment by gelguy** [comment]
`nvim-fzf` works different from `wilder`, so it is still difficult to write an FZF file finder pipeline. I don't have any plans for this.

One alternative is to adapt https://github.com/nvim-telescope/telescope-fzf-native.nvim as a filter, similar to how https://github.com/romgrk/fzy-lua-native is used in `wilder#lua_fzy_native()`.
