### ISSUE TITLE
No history is saved

### ISSUE THREAD

**Issue by Dich0tomy** [gelguy/wilder.nvim#152]
Hey. After a while of using wilder I noticed that history is not being saved. What can I do about this? This is my config:
```lua
local wilder = require 'wilder'

wilder.setup {
	modes = {':', '/', '?'},
	next_key = '<Tab>',
	previous_key = '<S-Tab>',
}

wilder.set_option('pipeline', {
	wilder.branch(
		wilder.cmdline_pipeline(),
		wilder.search_pipeline()
	),
})

wilder.set_option('renderer', wilder.wildmenu_renderer({
	highlighter = wilder.basic_highlighter(),
	separator = ' · ',
	left = {' ', wilder.wildmenu_spinner(), ' '},
	right = {' ', wilder.wildmenu_index()},
}))
```

**Comment by gelguy** [comment]
Thanks for the bug report! I'm not able to reproduce this at the moment.

Could you provide the output of `:version`?

This might caused by https://github.com/gelguy/wilder.nvim/issues/30. For older versions of Neovim (0.5 and lower), the `<Up>` and `<Down>` keys don't work correctly in cmdline mode.

**Comment by Dich0tomy** [comment]
Alright. So I noticed the history only works locally, but not across runs.

https://user-images.githubusercontent.com/75364377/185116682-fc4c9aab-b650-4bc3-be08-617e47da1428.mp4

The output of :version is
```
NVIM v0.8.0-dev-788-g0fdf59ac9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-443

Features -acl +iconv +tui
...
```
```

**Comment by gelguy** [comment]
Does this occur in terminal Neovim? Or only in Neovide.

I wasn't able to set up Neovide correctly for Debian, so I'm unable to debug it at the moment.

**Comment by Dich0tomy** [comment]
Nope, not saved in console nor nvim-qt.

**Comment by gelguy** [comment]
A few more questions:
1. Does this occur even when `wilder` is removed?
2. Does this occur when disabling `wilder` before quitting Neovim (with `:call wilder#disable()`)?

**Comment by Dich0tomy** [comment]
Alright that's really weird but it looks that it happens even without wilder, in nvim-qt, nvim and neovide. So it appears there's something wrong with my enviroment/configuration.
