### ISSUE TITLE
Python initilization failed

### ISSUE THREAD

**Issue by sutheim** [gelguy/wilder.nvim#154]
Hey guys I'm a novice vimmer trying to get wilder working. I love the plugin but I'm running into some issues with Python.

Windows 10
nvim 0.7.2
Latest wilder installed with packer in lua using one of the configs from the readme

On startup I'm getting this message:
```
wilder: Python initilization failed
Vim(call):E117: Unknown function: _wilder_init
```

However python seems to be set up as when running chechhealth provider i get this:
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:\Program Files\Python310\python.exe"
  - INFO: Executable: C:\Program Files\Python310\python.exe
  - INFO: Python version: 3.10.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

I see mentions of :UpdateRemotePlugins on other threads but this command is not available to me ( neither am I'm running this remotely if that matters )

**Comment by gelguy** [comment]
The `:UpdateRemotePlugins` command should be available if you've set up your Neovim environment correctly.

Can you check the output if `:verbose command UpdateRemotePlugins`?
If that fails, can you check `:filter rplugin scriptnames`?
If the output is empty, can you check `:echo $VIMRUNTIME`?

**Comment by sutheim** [comment]
Thanks I had a look into it following the steps you outline, as at first I didn't realize the UpdateRemotePlugins command was so essential in my local-only context and I found that it was being disabled by another plugin. After re-enabling it I was able to fix my wilder issue by running UpdateRemotePlugins.
