### ISSUE TITLE
[Discussion] Implementation details of command palette 

### ISSUE THREAD

**Issue by smjonas** [gelguy/wilder.nvim#156]
Apologies for this issue since this is more of a discussion - but I couldn't find another place to ask this :) 
For my plugin [inc-rename.nvim](https://github.com/smjonas/inc-rename.nvim), I am trying to control a buffer while typing in the command line to add support for plugins such as [dressing.nvim](https://github.com/stevearc/dressing.nvim). I was made aware of your command palette in wilder.nvim in [this issue](https://github.com/smjonas/inc-rename.nvim/issues/17) and thought I might ask for some details here.

I checked the code but since I'm not good at Vimscript, I couldn't find what I was looking for.

Therefore, I'm asking: could you describe in a few sentences how you achieved typing in the command line and the command palette at the same time? 

Thanks for your time!

**Comment by gelguy** [comment]
No worries, the rough skeleton looks something like:
```lua
local buf = vim.api.nvim_create_buf(false, true)
local win = -1

function _G.enter()
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, {})
  win = vim.api.nvim_open_win(buf, 0, {
    relative = 'editor',
    height = 1,
    width = 100,
    row = 0,
    col = 0,
  })
  vim.cmd('redraw')
end

function _G.change()
  local cmdline = vim.fn.getcmdline()
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, {cmdline})
  vim.cmd('redraw')
end

function _G.leave()
  vim.api.nvim_win_close(win, true)
  vim.cmd('redraw')
end

vim.cmd('autocmd CmdlineEnter * call v:lua.enter()')
vim.cmd('autocmd CmdlineChanged * call v:lua.change()')
vim.cmd('autocmd CmdlineLeave * call v:lua.leave()')
```
Basically a new window is created on `CmdlineEnter`, the text is updated with `getcmdline()` on `CmdlineChanged`, and the window is closed on `CmdlineLeave`.

There's a lot of other things to handle (e.g. using `vim.schedule()` to avoid `textlock`) but most importantly: `redraw` is disabled when the `inccommand` preview is active. See https://github.com/neovim/neovim/pull/9783. `wilder` pretty much doesn't work when `inccommand` is active and always `redraw`s 1 frame late.

Edit: Clarification - `redraw` is only disabled when triggered by events/timers (e.g. callback from a remote plugin, `vim.schedule()`).

I'll be happy to explain more if you have any questions.

**Comment by smjonas** [comment]
Thank you very much for your help, I really appreciate it! I have managed to implement the feature based on your code :) For some reason, `redraw` did not seem necessary to get this working for me though.

**Comment by smjonas** [comment]
There is one minor thing that I wasn't able to implement which is showing the cursor in the window as the user types the command. I was not able  to achieve this using this code after the window has been opened:
```lua
vim.api.nvim_win_set_cursor(input_win_id, { 1, 1 })
-- I also tried adding a vim.cmd("redraw") afterwards which didn't help
```
Any insights on this? I saw that you also used `nvim_win_set_cursor` but maybe I'm missing something. 

Thanks for your time! :)

**Comment by gelguy** [comment]
In cmdline mode, the cursor will be positioned in the cmdline, and so the cursor won't appear in the window even if you call `set_cursor()`.

The "cursor" in `wilder` is drawn in with a highlight. You can get the cursor position with `getcmdpos()` and then apply the highlight with `nvim_buf_add_highlight()`.

**Comment by smjonas** [comment]
This fake cursor is better than no cursor at all :D thanks again!
