### ISSUE TITLE
pipeline: Vim(call): Unknown function: _wilder_python_search

### ISSUE THREAD

**Issue by bench87** [gelguy/wilder.nvim#158]
when I press / command i got error `pipeline: Vim(call): Unknown function: _wilder_python_search` How can i fix it?

**Comment by ratheesh** [comment]
If you are using `neovim`, executing `:UpdateRemotePlugins` command generally fix the issue for me. This especially occurs after running `PackerSync` or `PlugUpdate `command.
Please check if this helps.

**Comment by bench87** [comment]
I solved by PackerSync command, Thank you

**Comment by chrisgrieser** [comment]
Thanks, `UpdateRemotePlugins` was also necessary for me.
