### ISSUE TITLE
Neovim Python Error when entering command mode

### ISSUE THREAD

**Issue by Gavinok** [gelguy/wilder.nvim#16]
NVIM v0.4.2
Vi IMproved 8.1
python Version: 3.7.4
pynvim Version: 0.3.2

After starting up neovim and entering any of the supported command lines eg ':' '?' or '/' I get the following error. After the error goes away the auto suggestion works great. When using regular vim the issue does not persist so I assume its part of the neovim python integration. The error seems to becoming from autoload/wilder/main.vim on line 66. When I comment out the line the error doesn't appear. I have only added the minimal settings from the help file.

 Error detected while processing function
<lambda>3[1]
<SNR>23_start[8]
 E117: unknown function: _wilder_init

Keep up the great work on this awesome plugin!

**Comment by Gavinok** [comment]
I was mistaken the search also doesnt seem to work and has a similar issue except instead of printing an error the wildmenu is blank and a quick message pops up saying 
> wilder: draw: Vim(if):E731: using Dictionary as a String
not an issue in normal vim and solves is resolved by

**Comment by gelguy** [comment]
Hi, thanks for using the plugin!

Could you paste the `python3` and `wilder` settings from your `init.vim`?

If the error is that `_wilder_init` is not found, there is a chance that your `python3` is not set up correctly.

Could you run `:checkhealth` and paste the output here as well?

**Comment by Gavinok** [comment]
The issue still happens with only vim-plug as the plugin manager and wilder.nvim as the only plugin

- Here is the output of my python checkhealth
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.4
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

- Here are all my wilder based settings
" Quick Init {{{1 "
let g:python_host_prog  = '/usr/bin/python2' "speed up python2 startup
let g:python3_host_prog = '/usr/bin/python3' "speed up python3 startup
" 1}}} "Quick Init

**Comment by gelguy** [comment]
Could you try running `:UpdateRemotePlugins` and then restarting nvim?

 I was under the assumption `vim-plug` would automatically run this for Neovim plugins but looks like my assumption is wrong.

**Comment by Gavinok** [comment]
thanks that  got it working! really apreciate the help!

**Comment by i3d** [comment]
hmm... I just installed this plugin and got this issue again. I wonder whether there is a more obvious to discover this manual operation or whether there is a way to automate it so we don't have to :UpdateRemotePlugins.

**Comment by gevorg-vardanyan-im** [comment]
Hi there, I see that this issue is closed, but anyway want to share this code block for lazy.nvim users.
you can add this code block in config to avoid manual command running:

> vim.cmd([[
    augroup WilderSetup
    autocmd!
    autocmd VimEnter * call wilder#enable_cmdline_enter()
    autocmd VimEnter * silent! UpdateRemotePlugins
    augroup END
]])
