### ISSUE TITLE
`_wilder_python_search` error when searching with `/`

### ISSUE THREAD

**Issue by wbehrens-on-gh** [gelguy/wilder.nvim#188]
I installed wilder using lazy
```lua
{
  'gelguy/wilder.nvim',
  config = function()
    require('wilder').setup({
      modes = {':', '/', '?'}
    })
  end,
},
```
but when I try and search with `/` I get `pipeline: Vim(call):E117: Unknown function: _wilder_python_search`

Unrelated but what makes the menu look like https://github.com/gelguy/wilder.nvim#popupmenu-renderer with borders and transparency?

**Comment by doganalper** [comment]
Try running `checkhealth`. I had same issue and after checking it it tells me to run the script `UpdateRemotePlugins` that fixed this error.

**Comment by wookayin** [comment]
With lazy.nvim you can do

```
{
  'gelguy/wilder.nvim',
  config = function()
    require('wilder').setup({
      modes = {':', '/', '?'}
    })
  end,
  build = ':UpdateRemotePlugins'
},
```

Note: if you have any other plugins that also make use of remote plugins and therefore require `UpdateRemotePlugins`, this build command might break the others. This is a current limitation of lazy.nvim; in which case you can run `:UpdateRemotePlugins` manually after all the plugins have been installed.
