### ISSUE TITLE
[Feature Request] Support pum for command line mode in neovim

### ISSUE THREAD

**Issue by ratheesh** [gelguy/wilder.nvim#2]
Support for popup menu in command line mode was recently merged in neovim.

Can we support this in this plugin?

**Comment by gelguy** [comment]
This plugin does not use the native `wildmenu`, but instead simulates it (currently by using either the statusline or a floating window).

Adding support for `pum` would require simulating the `pum` using a floating window. It is possible, but would require quite a bit of effort, and is not a priority for me right now.

**Comment by ratheesh** [comment]
Thanks for the reply. I am closing this.
