### ISSUE TITLE
How to disable foldcolumn for floating window

### ISSUE THREAD

**Issue by weilbith** [gelguy/wilder.nvim#23]
Hey,
first I like to thank you for this amazing plugin! :pray: 

I just did the setup and I'm super happy. Unfortunately there is this tiny cosmetic issue of a gap on the left side:

![screenshot_1606000663](https://user-images.githubusercontent.com/12543647/99889745-78c73f00-2c58-11eb-91ee-eea764900b85.png)

I suppose that it is the foldcolumn that is visible there. I'm using a recent NeoVim version, so the renderer should open a floating window. Do you have a specific filetype for the displayed buffer which would allow to disable the option there?

This is my configuration. So there should be actually no gap and in your screenshots I can't see such neither.

```vim
call wilder#set_option('modes', ['/', '?', ':'])
call wilder#set_option('renderer', wilder#float_renderer({
      \   'separator': ' • ',
      \   'separator_hl': 'Grey',
      \   'hl': 'GreenBold',
      \   'left': [
      \     {
      \       'value': [
      \         wilder#condition(
      \           { -> getcmdtype() ==# ':' },
      \           ' COMMAND ',
      \           ' SEARCH '
      \         ),
      \         '',
      \       ],
      \       'hl': 'RedBackground',
      \     },
      \     ' ',
      \   ],
      \   'right': [
      \     ' ',
      \     wilder#index({ 'hl': 'YellowBold' }),
      \   ],
      \ }))
```

**Comment by gelguy** [comment]
Thanks for the bug report!

This should be fixed by #24.
