### ISSUE TITLE
Function call depth is higher than 'maxfuncdepth'

### ISSUE THREAD

**Issue by gennaro-tedesco** [gelguy/wilder.nvim#27]
Was there a recent update to the plugin? Today I noticed that all of a sudden I am getting the error:
```
Error detected while processing function wilder#separator[1]..wilder#separator[1]..wilder#separator[1]..wilder#separator[1]..wilder#separat
or[1]..wilder#separator[1]..wilder#separator[1]..wilder#separator[1]..wilder#separator[1]..wilder#separator[1]..wilder#separator[1]..wilder
#separator[1]..wilder#separator[1]..wilder#separator[1]
...
...
E132: Function call depth is higher than 'maxfuncdepth'
```
at (neo)vim start-up. After dismissing the error the functionalities of the plugin do not really work. 

Setup 
```
nvim -v
NVIM v0.5.0-dev+1083-g1aec5ba85
Build type: Release
LuaJIT 2.1.0-beta3

macOs Big Sur 
11.2.2
```

**Comment by gelguy** [comment]
Apologies! I just did an update today.

#28 should fix the issue.

**Comment by gennaro-tedesco** [comment]
I `:PlugUpdate` and I confirm it works fine now.

Thank you very much for the quick fix, I could not imagine a life without your plugin! :D
