### ISSUE TITLE
Neovim incsearch highlighting tracking issue

### ISSUE THREAD

**Issue by gelguy** [gelguy/wilder.nvim#30]
`incsearch` highlighting disappears or is sometimes wrong

- [All versions] Occurs when using `wilder#popupmenu_renderer()` when searching
- [Neovim 0.5] Occurs for both `wilder#popupmenu_renderer()` and `wilder#wildmenu_renderer()` when searching and the current window view changes (e.g. moves due to `incsearch`)

See https://github.com/neovim/neovim/issues/14064
See https://github.com/neovim/neovim/pull/12495 (outdated)

A workaround is to use `wilder#wildmenu_renderer({'mode': 'statusline'})` for searching.

Update: the `statusline` workaround doesn't work for Neovim 0.6 nightly.

**Comment by Racle** [comment]
Changing mode doesn't work if you're using also scrollbar plugin (I'm using [dstein64/nvim-scrollview](https://github.com/dstein64/nvim-scrollview) and Neovim 0.5).

If file fits to screen, search highlighting works as intended (there is no scrollbar). If file is large and scrollbar becomes visible, wilder will break `incsearch` highlight.

Quickly way to test this out is to install `scrollview` and `wilder`, enable `incsearch` and try with small and large file.

**Comment by gelguy** [comment]
The underlying root cause for the case with the scrollbar plugin is the same (neovim/neovim#14064) .

An oversimplified explanation: when redrawing windows, highlights are invalidated in some cases. If the viewport does not change too much, the rendering doesn't invalidate the window so the highlights are kept. However, if the viewport changes too much, or if there is a floating window overlaying the window, the highlights are invalidated.

Unfortunately I don't have a workaround for this.

**Comment by tzachar** [comment]
I don't think this is related to [nvim-scrollview](https://github.com/dstein64/nvim-scrollview). I encountered the same behavior, and am not using that plugin.
The problem usually arises when `incsearch` is enabled and searching for something not in the current viewport.
As you can see in the attached screen grab, for some reason the search reverts back to the previous searched for item on each key stroke.
![wilder](https://user-images.githubusercontent.com/4946827/128818901-7b5eedf5-7844-4827-be31-36ccc93ca031.gif)

**Comment by gelguy** [comment]
I updated the original issue just yesterday - the `statusline` workaround does not work for Neovim 0.6 nightly.

Unfortunately I don't have another workaround for this.

**Comment by tzachar** [comment]
10x. Added a confirmation on the nvim bug you opened. 
Any idea what is the cause?

**Comment by gelguy** [comment]
I bisected to the problematic commit in the issue mentioned above (https://github.com/neovim/neovim/issues/14064).

In general, Neovim/Vim doesn't like it when `redraw` is called in the cmdline. The `incsearch` highlighting is a "temporary" highlight, and it gets invalidated when redrawing in certain cases e.g. the viewport moves or there is a floating/popup window over the buffer.

**Comment by tzachar** [comment]
Then maybe the solution would be to update `incsearch` proactively after calling `redraw`? or not call `redraw` at all?

**Comment by gelguy** [comment]
I've tried many workarounds, but none work so far. Fixing the code in Neovim seems to be the best option.

**Comment by gelguy** [comment]
I've found another workaround 😄.

Could you help verify if the latest master fixes the issue? It should be fixed for all renderers and all Neovim versions.

**Comment by Gelio** [comment]
Yay :tada: I'm using Neovim nightly and the issue seems to indeed be fixed. I've tested with both `wildmenu_renderer` and `popupmenu_renderer` and in both cases the `incsearch` highlight is stable :smile: 

Thanks for fixing it!

**Comment by Frederick888** [comment]
Hate to be that guy but there's still a minor issue for me...

I'm using neovim 0.5.0 and when the first search hit is not in the view before starting searching, the highlights flicker sometimes:

https://user-images.githubusercontent.com/4507647/128875221-0c7388ba-4f69-4b3e-9b08-6c1a06e2e7bc.mp4

The minimal vimrc I used:
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

" vim-plug
call plug#begin()
Plug 'gelguy/wilder.nvim'
call plug#end()

set incsearch

" wilder.nvim
call wilder#enable_cmdline_enter()
set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
cmap <expr> <C-n> wilder#in_context() ? wilder#next() : "\<C-n>"
cmap <expr> <C-p> wilder#in_context() ? wilder#previous() : "\<C-p>"
call wilder#set_option('modes', ['/', '?', ':'])
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     [
      \       wilder#check({_, x -> empty(x)}),
      \       wilder#history(),
      \       wilder#result({
      \         'draw': [{_, x -> ' ' . x}],
      \         }),
      \     ],
      \     wilder#cmdline_pipeline(),
      \     wilder#search_pipeline(),
      \   ),
      \ ])
if has('nvim')
  call wilder#set_option('renderer', wilder#renderer_mux({
        \ ':': wilder#popupmenu_renderer({
        \       'highlighter': wilder#basic_highlighter(),
        \       'left': [
        \         wilder#popupmenu_devicons(),
        \         ],
        \       'right': [
        \         ' ',
        \         wilder#popupmenu_scrollbar(),
        \         ],
        \       }),
        \ '/': wilder#wildmenu_renderer({
        \       'highlighter': wilder#basic_highlighter(),
        \       }),
        \ '?': wilder#wildmenu_renderer({
        \       'highlighter': wilder#basic_highlighter(),
        \       }),
        \ }))
else
  call wilder#set_option('renderer', wilder#wildmenu_renderer({
        \ 'highlighter': wilder#basic_highlighter(),
        \ }))
endif

" vim: set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab:
```

**Comment by Frederick888** [comment]
Wait... I'm so sorry... I played around with the files locally and there were conflicts when git pull so my wilder.nvim wasn't really up-to-date (face palm...)

Just updated and now the issue is gone. Thank you very much for the fix!

**Comment by tzachar** [comment]
#65 fixes the issue for me.
10x
