### ISSUE TITLE
Completion contents are wrong when searching with ~

### ISSUE THREAD

**Issue by Matts966** [gelguy/wilder.nvim#36]
## Expected behavior

```vim
:cd ~/<wildcharm>
```
→  completes home directory contents

## Actual behavior

```vim
:cd ~/<wildcharm>
```

→ completes root(/) directory contents

**Comment by gelguy** [comment]
Thanks for the bug report!

I can reproduce this.

**Comment by gelguy** [comment]
This should be fixed as part of the changes in #37.

Could you try with the latest `master`?

**Comment by Matts966** [comment]
@gelguy 
Thank you for your quick fix!!! 🚀 
This was fixed in my env too. I will close this.
