### ISSUE TITLE
Assigning custom names for different modes

### ISSUE THREAD

**Issue by ratheesh** [gelguy/wilder.nvim#4]
Currently, can we assign custom names to different modes( `'/' ,'?', ':'` )? 
If not, it will be nice to have this.

**Comment by gelguy** [comment]
If you mean whether you can change what is shown on the statusline based on the mode, you can achieve this by checking `getcmdtype()`.
```vim
call wilder#set_option('renderer', wilder#statusline_renderer({
      \ 'left': [
      \   {'value': {-> getcmdtype() ==# ':' ? ' COMMAND ' : ' SEARCH '}, 'hl': s:mode_hl},
      \   wilder#string(' ', s:status_hl),
      \ ],
      \ }))
```

**Comment by ratheesh** [comment]
Thank you. This is working.
