### ISSUE TITLE
Floating window renderer masks cmdline messages

### ISSUE THREAD

**Issue by romgrk** [gelguy/wilder.nvim#41]
*Description*:
Command line messages are cleared when wilder is activated with the floating window renderer.

*Actual (with wilder)*:
![GIFrecord_2021-04-06_071115](https://user-images.githubusercontent.com/1423607/113702414-77e2f700-96a7-11eb-8c89-ec26ee2bcb67.gif)

*Expected (without wilder)*:
![GIFrecord_2021-04-06_071159](https://user-images.githubusercontent.com/1423607/113702415-77e2f700-96a7-11eb-9c25-502a6f51c2d9.gif)

**Comment by gelguy** [comment]
I can reproduce this with the configuration:

```vim
set cmdheight=2

" Neovim sets F by default
set shortmess-=F
```

**Comment by gelguy** [comment]
This is a bug in Neovim, see: https://github.com/neovim/neovim/issues/14304

**Comment by gelguy** [comment]
I've found a workaround for this:
```vim
function! SetShortmessF(on) abort
  if a:on
    set shortmess+=F
  else
    set shortmess-=F
  endif
  return ''
endfunction

nnoremap <expr> : SetShortmessF(1) . ':'

augroup WilderShortmessFix
  autocmd!
  autocmd CmdlineLeave * call SetShortmessF(0)
augroup END
```

This involves rebinding `:`, so use the mapping with caution. If there are errors, you can unbind the mapping by entering the command-line window with `q:`.

**Comment by gelguy** [comment]
Fixed in https://github.com/neovim/neovim/pull/18251.
