### ISSUE TITLE
Honor wildignorecase when searching files with :e[dit]

### ISSUE THREAD

**Issue by rafi** [gelguy/wilder.nvim#42]
I like having `wildignorecase` enabled and quickly edit files with `:e[dit]`.
For example, `:e rea<Tab>` should match `README.md`.

Very cool plugin, thanks!

**Comment by gelguy** [comment]
Thanks! I'll update this in a later version.

For a workaround, if you enable the `fuzzy` option for the `cmdline_pipeline` it will do fuzzy matching which also ignores casing.

e.g.
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline({
      \       'fuzzy': 1,
      \     }),
      \     wilder#python_search_pipeline(),
      \   ),
      \ ])
```

where `:e rm` will match `README.md`

**Comment by gelguy** [comment]
I was tinkering about with this and reached the conclusion that this is better implemented as a separate filter.

```vim
function! s:wildignorecase_filter(ctx, xs, data)
  let l:expand = get(a:data, 'cmdline.expand')
  let l:ignorecase = &wildignorecase && (l:expand ==# 'dir' || l:expand ==# 'file')
  let l:q = get(a:data, 'cmdline.match_arg', '')
  return empty(l:q) ? a:xs :
      \ filter(a:xs, {_, x -> l:ignorecase ? x[0 : len(l:q) - 1] ==? l:q : x[0 : len(l:q) - 1] ==# l:q})
endfunction

call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline({
      \       'fuzzy': 1,
      \       'fuzzy_filter': {ctx, xs, q -> xs},
      \     }) + [wilder#result({
      \       'value': funcref('s:wildignorecase_filter'),
      \     })],
      \     wilder#python_search_pipeline(),
      \   ),
      \ ])
```

The `fuzzy_filter` returns all the candidates and `s:wildignorecase_filter` filters the candidates accordingly. To get correct highlighting, use the `wilder#basic_highlighter()` with the `case_sensitive: 0` option.

I still recommend using `fuzzy: 1` with the default filters as shown in the above comment.
