### ISSUE TITLE
Do you have any plans to move from RemotePlugin to Lua in Neovim?

### ISSUE THREAD

**Issue by yutkat** [gelguy/wilder.nvim#44]
I don't like remote-plugins.

Do you have any plans to change the https://github.com/gelguy/wilder.nvim/blob/master/rplugin/python3/wilder/__init__.py to Lua?

**Comment by gelguy** [comment]
One big issue with Lua is that the CPU-intensive operations are blocking. This means that tasks like regex search across a large buffer or fuzzy matching over a large number of candidates will block - I believe Telescope faces this issue (there might be progress on the threading side but I have not been following too closely).

I have experimented with spawning threads using `vim.loop.new_work()`  but it doesn't have first class support (e.g. `require()` does not look up Neovim's plugin path). Cancellation of the worker is also not supported so you can run into issues where too many tasks are created when the cmdline changes quickly (e.g. from using a `cmap`).

If there is better threading support for Lua in the future, I might port the Python remote plugin to Lua (especially if there are performance gains), but as of now, the Python remote plugin will continue to be used.

Also, using the Python remote plugin also allows for Vim compatibility by using `nvim-yarp`.

**Comment by yutkat** [comment]
Thank you for your comment👍  I understood it.

**Comment by IndianBoy42** [comment]
Telescope recently implemented async support for the searching, really improving the performance there. Maybe you could look at that and see if their approach would work for wilder as well?
