### ISSUE TITLE
Option to reverse wilder#history

### ISSUE THREAD

**Issue by Matts966** [gelguy/wilder.nvim#47]
Thank you for releasing this great plugin!

Current wilder shows history on popup menu in reverse order compared to the default popup history.

It would be great if we could change the order by an option.

**Comment by gelguy** [comment]
Thanks for using!

Do you mean that you wish to reverse the order of the candidates in `wilder#history()`? This can be done by adding:
```
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     [
      \       wilder#check({_, x -> empty(x)}),
      \       wilder#history(),
      \       {_, xs -> reverse(xs)},
      \     ],
      \     ... other pipelines ...
      \   ),
      \ ])
```

**Comment by Matts966** [comment]
It's almost perfectly what I wanted! Very appreciated :bow:

Could I scroll from bottom? The scroll bar starts from top by default in my environment.
<img width="473" alt="スクリーンショット 2021-07-06 2 48 13" src="https://user-images.githubusercontent.com/28551465/124505525-ab4b3400-de04-11eb-8755-6c5f19da37ae.png">

**Comment by gelguy** [comment]
There's a hidden `reverse` option for `wilder#popupmenu()`:
```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'reverse': 1,
      \ ... other options ...
      \ }))
```

It's hidden for now since I might change it in the future (having to handle `reverse` might restrict newer features in the future). If I find a good solution for it I will add it as a proper documented feature.

**Comment by Matts966** [comment]
Thank you for you explanation! I was satisfied with `{_, xs -> reverse(xs)},` solution!

Please feel free to leave this issue for tracking or close for other tickets.

**Comment by Matts966** [comment]
For anyone who want to try `reverse` option, the configuration example is below.

```vim
call wilder#enable_cmdline_enter()
" only / and ? are enabled by default
set wildcharm=<Tab>
" For :cd ~/<C-n> to complete path
cmap <expr> <C-n> wilder#in_context() ? wilder#previous() : "\<C-n>"
cmap <expr> <C-p> wilder#in_context() ? wilder#next() : "\<C-p>"
call wilder#set_option('modes', [':'])
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'highlighter': wilder#basic_highlighter(),
      \ 'reverse': v:true,
      \ }))
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     [
      \       wilder#check({_, x -> empty(x)}),
      \       wilder#history(),
      \     ],
      \     wilder#cmdline_pipeline(),
      \     wilder#search_pipeline(),
      \   ),
      \ ])
```
