### ISSUE TITLE
Issue with cpsm

### ISSUE THREAD

**Issue by farzadmf** [gelguy/wilder.nvim#49]
Hi, sorry that I'm asking an issue about `cpsm` here, but I looked at their repo and seems to be pretty dormant for quite a while and your plugin is the only reason I found out about them in the first place :wink: 

The "recommended" advanced Neovim configuration mentions that we need `cpsm`. Just adding it to `vimplug` doesn't seem to be enough because I see this error in neovim:
```
python_cpsm_filt: No module named 'cpsm_py'
```

I think we need to run their `./install.sh`, but when I run it, I see the following errors:
```
PY3 not specified; inferring Python version from /usr/bin/vim
Python 3 selected
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at /usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options)
Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.21/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)
  CMakeLists.txt:21 (find_package)
```

Can you help me please?

**Comment by gelguy** [comment]
There are additional steps to build the binary after installing the plugin with a plugin manager.

You can find additional details in step 2 of https://github.com/nixprime/cpsm#installation.

**Comment by gelguy** [comment]
Edit: Ah, I see you've run `./install.sh`.

The error might be due to missing Boost library as seen under the https://github.com/nixprime/cpsm#requirements.

For Ubuntu you would run `apt install libboost-all-dev` (do so for the other missing requirements, if any).

**Comment by farzadmf** [comment]
Thank you for your very quick reply @gelguy 

I'm running Manjaro (Arch-based), and I had to install `boost` package, and `./install.sh` seems to be fine for `cpsm`

Just one question: is there anything to do to check if it actually worked, because, if I remember correctly, even when `./install.sh` was giving error (and I was seeing that error in neovim), doing `:e <TAB>` would still show me some options (I think coming from `wilder`)

**Comment by gelguy** [comment]
Some parts of the completion are done in Vim (e.g. command completions), others are done using the Python remote plugin (e.g. file completions, help completions) for performance reasons, so the non-Python completions would still work even if the remote plugin is not set up correctly.

Unfortunately there isn't a health check of sorts to see if everything works out. The best way to check would be to try to attempt `:` command completions, `:help` completions, `:e` file completions and `/` search completions. I think these 4 should cover all the cases currently (i.e. do `:<TAB>`, `:help <TAB>`, `:e <TAB>` and `/<TAB>`).

**Comment by farzadmf** [comment]
> (i.e. do `:<TAB>`, `:help <TAB>`, `:e <TAB>` and `/<TAB>`).

OK, now I'm confused. Maybe I'm not using this correctly, but:
- When I type `:` _a_ menu appears automatically and I don't need to press `<TAB>` for something to appear.
- Same goes with `:help` and `:e` (no need for `<TAB>` and something appears as soon as I type a `<SPACE>`
- As for `/`, I don't think anything special happens for that :thinking: if I type `/<TAB>`, the only thing that happens is that my last search is put after `/`

Am I using this correctly? Is it another plugin I don't know about doing this (I have _a lot of_ plugins)? :stuck_out_tongue_closed_eyes:

**Comment by gelguy** [comment]
Could you provide the configuration you are using?

**Comment by farzadmf** [comment]
Sorry for the delay @gelguy , I basically copy/pasted from the `README`; this is what I have regarding `wilder`:
```
call wilder#enable_cmdline_enter()
set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
call wilder#set_option('modes', ['/', '?', ':'])

function! s:wilder_init() abort
  call wilder#set_option('pipeline', [
        \   wilder#branch(
        \     wilder#python_file_finder_pipeline({
        \       'file_command': {_, arg -> stridx(arg, '.') != -1 ? ['fd', '-tf', '-H'] : ['fd', '-tf']},
        \       'dir_command': ['fd', '-td'],
        \       'filters': ['cpsm_filter'],
        \       'cache_timestamp': {-> 1},
        \     }),
        \     wilder#cmdline_pipeline({
        \       'fuzzy': 1,
        \       'fuzzy_filter': wilder#python_cpsm_filter(),
        \       'set_pcre2_pattern': 0,
        \     }),
        \     wilder#python_search_pipeline({
        \       'pattern': wilder#python_fuzzy_pattern({
        \         'start_at_boundary': 0,
        \       }),
        \     }),
        \   ),
        \ ])

  let s:highlighters = [
        \ wilder#pcre2_highlighter(),
        \ wilder#lua_fzy_highlighter(),
        \ ]

  call wilder#set_option('renderer', wilder#renderer_mux({
        \ ':': wilder#popupmenu_renderer({
        \   'highlighter': s:highlighters,
        \   'left': [
        \     wilder#popupmenu_devicons(),
        \   ],
        \   'right': [
        \     ' ',
        \     wilder#popupmenu_scrollbar(),
        \   ],
        \ }),
        \ '/': wilder#wildmenu_renderer({
        \   'highlighter': s:highlighters,
        \ }),
        \ }))
endfunction " s:wilder_init

augroup my_wilder_init
  autocmd!
  autocmd CmdlineEnter * ++once call s:wilder_init()
augroup END
```

BTW, I _think_ the section for [faster startup time](https://github.com/gelguy/wilder.nvim#faster-startup-time) is missing a `call` after `++once ...`

**Comment by gelguy** [comment]
Thanks, I've updated the README.

`fzy-lua-native` which is used by the `lua_fzy_highlighter` is likely not installed correctly. You can install it with a plugin manager e.g. `Plug romgrk/fzy-lua-native`.

If it still doesn't work, try switching highlighters:
```vim
  let s:highlighters = [
        \ wilder#pcre2_highlighter(),
        \ wilder#basic_highlighter(),
        \ ]
```

Check `:mess` for any errors too.

**Comment by farzadmf** [comment]
> I've updated the README

:+1: 

> is likely not installed correctly

I do have the ling `Plug 'romgrk/fzy-lua-native'` in my config, and it seems to be installed.

As I was typing this, I just realized that I've mapped my `/` and `?` to use [incsearch](https://github.com/haya14busa/incsearch.vim) (not sure a good idea, but to be decided :stuck_out_tongue_closed_eyes: )

Now I have a new question: is there any way to bind `wilder` to another shortcut  in the config instead of `/`:
```vimL
" ....
\ '/': wilder#wildmenu_renderer({
\   'highlighter': s:highlighters,
\ }),
\ }))
" ...
```

I tried changing to something like `'w/`: ...` (just an example), but that didn't seem to have any effect

**Comment by gelguy** [comment]
https://github.com/haya14busa/incsearch.vim is incompatible with `wilder` since it's not actually using the cmdline - it's emulating the cmdline using https://github.com/osyo-manga/vital-over.

`wilder` doesn't actually remap `/` or `?`, it uses `CmdlineEnter` and `CmdlineChanged` to detect cmdline input and show the results.

**Comment by farzadmf** [comment]
Ah OK, makes sense then. I think I'm gonna map another key to `incsearch`.

However I just noticed one thing: when I do `:` and `wilder` opens, everything is arragned vertically:
![image](https://user-images.githubusercontent.com/5768792/127893601-7e482f82-ad37-4dd8-ba93-dc1985d7fd48.png)

However, when I enter `/`, things are listed horizontally:
![image](https://user-images.githubusercontent.com/5768792/127893815-e679cb8c-beee-4f74-883e-2bc644e15d10.png)

Is the the expected behavior or I'm still missing something?

**Comment by gelguy** [comment]
This is due to the `renderer_mux`:
```vim
  call wilder#set_option('renderer', wilder#renderer_mux({
        \ ':': wilder#popupmenu_renderer({
        \   'highlighter': s:highlighters,
        \   'left': [
        \     wilder#popupmenu_devicons(),
        \   ],
        \   'right': [
        \     ' ',
        \     wilder#popupmenu_scrollbar(),
        \   ],
        \ }),
        \ '/': wilder#wildmenu_renderer({
        \   'highlighter': s:highlighters,
        \ }),
        \ }))
```
which says for `/` (and `?`) completions, use the `wildmenu_renderer` and for `:` completions, use the `popupmenu_renderer`.

If you want to just use 1 renderer for both you can remove the `renderer_mux` and directly set the `renderer` option to one of the renderers:
```vim
  call wilder#set_option('renderer', wilder#wildmenu_renderer())
```

Using the `popupmenu_renderer` isn't recommended for `/` searches since it blocks the buffer.

**Comment by farzadmf** [comment]
VERY NICE!

> Using the `popupmenu_renderer` isn't recommended for `/` searches

Good to know :slightly_smiling_face: 

Thanks for all the help @gelguy , I really appreciate it; closing this as my issue is solved

**Comment by farzadmf** [comment]
Hi @gelguy , I'm back with this problem 🙂, but this time, it's happening on a Mac,

This is related to `cpsm`, but I was hoping to get your help with it since, when I look at the issues there, I don't see much action going on recently.

I installed a few things to make the `./install.sh` move forward, but now it's failing with this message:
```
Python 3 selected by PY3=ON
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Boost: /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0") found components: program_options
-- Found PythonInterp: /Users/farzad/.asdf/shims/python3 (found suitable version "3.10.2", minimum required is "3")
-- Found PythonInterp: /Users/farzad/.asdf/shims/python3 (found version "3.10.2")
-- Found PythonConfig: -I/Users/farzad/.asdf/installs/python/3.10.2/include/python3.10 -I/Users/farzad/.asdf/installs/python/3.10.2/include/python3.10; -L/Users/farzad/.asdf/installs/python/3.10.2/lib/python3.10/config-3.10-darwin -lpython3.10 -lintl -ldl -framework CoreFoundation
-- Optional package ICU was not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/farzad/.vim/plugged/cpsm/build
[ 11%] Building CXX object CMakeFiles/cpsm_core.dir/src/str_util.cc.o
[ 22%] Linking CXX static library libcpsm_core.a
[ 22%] Built target cpsm_core
[ 33%] Building CXX object CMakeFiles/cpsm_py.dir/src/ctrlp_util.cc.o
[ 44%] Building CXX object CMakeFiles/cpsm_py.dir/src/python_extension.cc.o
[ 55%] Linking CXX shared library cpsm_py.so
ld: library not found for -lintl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cpsm_py.so] Error 1
make[1]: *** [CMakeFiles/cpsm_py.dir/all] Error 2
make: *** [all] Error 2
```

Do you think you can help me with this? I'd really appreciate it if you do

**Comment by gelguy** [comment]
There's a related issue on the `nixprime/cpsm`, could you check if following this workaround works for you?
https://github.com/nixprime/cpsm/issues/43#issuecomment-363298323

This comment also mentions that building with `asdf` fails but succeeds with `homebrew`: https://github.com/nixprime/cpsm/issues/43#issuecomment-891194971

**Comment by farzadmf** [comment]
Hey @gelguy , sorry for the super long delay, I hadn't gotten a chance to test it out.

I (think?) I finally managed to run `make install` on `cpsm` by forcing it to use my `brew` Python. However, now I have a new issue: as I start to type in the status line, I see the following message:
```
pipeline: Vim(return):E475: Invalid argument: Channel doesn't exist
```

To be honest with you, I have no idea where the message is coming from, and it's likely that it has nothing to do with `wilder` (since I see another "channel" error coming from another plugin).

Since you've been so nice to bear with me and my questions, do you know what could be wrong here?

**Comment by gelguy** [comment]
Can you check if there are other errors in `:messages`?

It's possible that the `cpsm` Python bindings are causing the Neovim's Python client to crash. Could you check by disabling `wilder` and checking if the channel errors still occur for other plugins?

You can also check if `cpsm` is working correctly by `cd`-ing to the `build` directory under the `cpsm` plugin installation directory and running `nvim` with the following commands:
```vim
python3 import os, sys
python3 sys.path.insert(0, os.getcwd())
python3 import cpsm_py
python3 print(cpsm_py.ctrlp_match(['a','b','c'], 'a'))
```

Another option is to check if there are errors in the Python client by running `NVIM_PYTHON_LOG_FILE=logfile NVIM_PYTHON_LOG_LEVEL=DEBUG nvim`. A `logfile` log will be generated under the current directory.

**Comment by farzadmf** [comment]
> Can you check if there are other errors in `:messages`?

That's actually the first place I checked before bothering you, but, for some reason, it's empty 🙁 

> Could you check by disabling `wilder` and checking if the channel errors still occur for other plugins?

I think when I comment out `wilder`, things are fine

> It's possible that the `cpsm` Python bindings are causing the Neovim's Python client to crash

This is very likely I think. Is it possible that it's because I forced `brew`'s version of `python` (instead of the `asdf` one I normally use) to run `make install` in `cpsm`?

> running `nvim` with the following commands

When I run `python3 import cpsm_py`, I see the following error:
```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 5 (python3-script-host):
ch 5 was closed by the client
```

Again, could it be because of the difference between `python`s?

**Comment by gelguy** [comment]
It's likely due to that. You can check by going to the `build` directory again, and just running `python` with `import cpsm_py`.

What's `g:python3_host_prog` set to in your config? You could try pointing it to `brew`'s `python` (remember to `pip install pynvim` for that `python`) and seeing if `python3 import cpsm_py` works fine.

**Comment by farzadmf** [comment]
That's it @gelguy , my `python3_host_prog` was pointing to the `asdf` one.

Although it would be aweome if I could make it work with the `asdf` one.

One nice thing with `asdf` was that I could point my `python3_host_prog` to `~/.asdf/shims/python`, but with homebrew, it seems that I have to point it to the specific version (e.g., `.../python@3.10/3.10.2/bin/python3`), and that means that every time my brew's python is updated, I need to update my `neovim` config as well

Do you, by any chance, know if there's any way around that?

**Comment by gelguy** [comment]
I don't have a Mac environment set up so I won't be able to help you further with Homebrew issues.

If there's a way to get the Python path which Homebrew is using, it's possible to set `python3_host_prog` dynamically e.g. for example `g:python_host_prog = system('brew which python') " doesn't work, used as an example`

**Comment by farzadmf** [comment]
Hey @gelguy , sorry to bother you again!

I was wondering if there's any way to get the command completion functionality without using `cpsm`.

Unfortunately, this plugin/library has caused nothing but trouble for me. Every time I do a single update on my system, it breaks, and I need to spend hours trying to fix it, and since it's dealting directly with C libraries on the system, and I have no idea how to link/pin/etc. those, it's just causing me pain and nothing else 😢

`wilder` is now a must-have in my everyday usage (I love what it does), but is there a way to get the same functionality (or similiar) without using `cpsm`?

**Comment by gelguy** [comment]
`cpsm` is optional so you can remove it from the config and replace it with something else.

For `wilder#python_cpsm_filter()`, you can replace it with `wilder#lua_fzy_filter()` (requires https://github.com/romgrk/fzy-lua-native) or `wilder#python_clap_filter()` (requires https://github.com/liuchengxu/vim-clap, see the README for installation instructions). Otherwise you can use `wilder#python_fuzzy_filter()` which requires no dependencies.

For `['cpsm_filter']` for the `filters` option in `wilder#python_file_finder_pipeline()`, you can use `['clap_filter']` (see above on vim-clap). For no dependencies, you can use the default of `['fuzzy_filter', 'difflib_sorter']`. Note that this makes the pipeline much slower if you have a large project/repository.

For `wilder#python_cpsm_highlighter()`, you can replace it with `wilder#lua_fzy_highlighter()` (see above for fzy-lua-native) or `wilder#python_pcre2_highlighter()` which has no dependencies.

**Comment by farzadmf** [comment]
Thank you so much @gelguy , I will definitely check the options as soon as I get the chance.

And I apologize if the comment was a bit "angry" because I was so frustrated. I managed to somehow "revert" the update and restore `cpsm` functionality until I properly look into replacing it for good.

I really appreciate you being so responsive and quick to reply, I wish everyone owning a library was like that. Thank you again!
