### ISSUE TITLE
Float renderer overwrites statusline in neovim

### ISSUE THREAD

**Issue by ratheesh** [gelguy/wilder.nvim#5]
I am using neovim built with the latest commit(as on today `c423ec65dcda1b5`).
I observe that float renderer is overwriting status line and also displaying line number. A sample screenshot is shown below 

 ![wilder_float_renderer](https://user-images.githubusercontent.com/70958/58490345-9c581900-818a-11e9-8900-7af10921af07.jpg)

Following is my renderer configuration:

call wilder#set_option('renderer', wilder#float_renderer({
                 \ 'separator':' • ',
                  \ 'separator_hl': s:sep_hl,
                  \ 'hl': s:status_hl,
                  \ 'left': [
                  \    {'value': [' WILDER', wilder#spinner()], 'hl': s:mode_hl},
                  \    wilder#separator('', s:mode_hl, s:status_hl, 'left'), ' ',
                  \ ],
                  \ 'right': [
                  \    ' ', wilder#separator('', s:index_hl, s:status_hl, 'right'),
                  \    wilder#index({'hl': s:index_hl}),
                  \ ],
                  \ }))

This setting works fine for `wilder#statusline_renderer()`
Can you please help me in configuring right settings?

**Comment by gelguy** [comment]
I've just built `f8f63393c12da88799cb480086922431de60ca0a` but am unable to reproduce this issue.

Could you provide a minimal `.vimrc` that can reproduce this issue?

**Comment by ratheesh** [comment]
I rebuilt neovim to matcher your build's commit number. I still see this issue.

screenshot:
![wilder_float_renderer_01](https://user-images.githubusercontent.com/70958/58533943-8177ba00-8207-11e9-91a7-10d9cf09677f.jpg)

**minimal .vimrc**
```
set runtimepath+=~/.vim
set packpath+=~/.vim
call plug#begin('~/.vim/plugged')
    Plug 'gelguy/wilder.nvim',         { 'do': ':UpdateRemotePlugins' }
call plug#end()

set number relativenumber
set cmdheight=1

call wilder#enable_cmdline_enter()
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
set wildcharm=<Tab>

hi WildStatus       ctermfg=250   ctermbg=234   cterm=NONE
hi WildMode       ctermfg=250   ctermbg=27    cterm=NONE
hi WildIndex        ctermfg=8       ctermbg=NONE  cterm=NONE
hi WildSeparator  ctermfg=108   ctermbg=234   cterm=NONE


let s:status_hl = wilder#make_hl('WilderStatus', 'WildStatus')
let s:mode_hl   = wilder#make_hl('WilderMode', 'WildMode')
let s:index_hl  = wilder#make_hl('WilderIndex', 'WildIndex')
let s:sep_hl    = wilder#make_hl('WilderSep', 'WildSeparator')

call wilder#set_option('pipeline', [
            \   wilder#branch(
            \     [
            \       wilder#check({_, x -> empty(x)}),
            \       wilder#history(15),
            \     ],
            \     wilder#cmdline_pipeline(),
            \     [
            \       wilder#python_fuzzy_delimiter(),
            \       wilder#python_search({'engine': 're'}),
            \       wilder#result_output_escape('^$,*~[]/\'),
            \     ],
            \   ),
            \ ])

call wilder#set_option('renderer', wilder#float_renderer({
            \ 'separator':' • ',
            \ 'separator_hl': s:sep_hl,
            \ 'hl': s:status_hl,
            \ 'left': [
            \    {'value': [{-> getcmdtype() ==# ':' ? ' Kommand ' : ' Suche '}, wilder#spinner()], 'hl': s:mode_hl},
            \    wilder#separator('', s:mode_hl, s:status_hl, 'left'), ' ',
            \ ],
            \ 'right': [
            \    ' ', wilder#separator('', s:index_hl, s:status_hl, 'right'),
            \    wilder#index({'hl': s:index_hl}),
            \ ],
            \ }))
call wilder#set_option('modes', ['/', '?', ':'])
```
Please include screenshot with float renderer in the main README file for reference.

**Comment by gelguy** [comment]
I have managed to reproduce the issue. This is due to the interaction of floats with `relativenumber`.

**Comment by ratheesh** [comment]
Thank you for fix this.

```doc/wilder.txt``` says that Floating renderer draws the results on a floating window **just above the cmdline**.

But in my case floating renderer is drawn on row overwriting status line. Is this expected?
