### ISSUE TITLE
Wrong candidate order (the result of sorting is not satisfactory)

### ISSUE THREAD

**Issue by jdhao** [gelguy/wilder.nvim#50]
This is a great plugin! I have found that the completion candidate order is not what I expect.

My config for wilder.nvim

```
call wilder#enable_cmdline_enter()
set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"

" only / and ? are enabled by default
call wilder#set_option('modes', ['/', '?', ':'])

call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline({
      \       'language': 'python',
      \       'fuzzy': 1,
      \     }),
      \     wilder#python_search_pipeline({
      \       'pattern': wilder#python_fuzzy_pattern(),
      \       'sorter': wilder#python_fuzzywuzzy_sorter(),
      \       'engine': 're',
      \     }),
      \   ),
      \ ])

call wilder#set_option('renderer', wilder#wildmenu_renderer({
      \ 'highlighter': wilder#basic_highlighter(),
      \ 'separator': '  ',
      \ 'right': [' ', wilder#wildmenu_index()],
      \ }))
```

When I type `:h vim.paste()`, I would expect that `vim.paste()` is ranked first in the completion item. However, it is rankded the last in the list of completion items (see image below)

![image](https://user-images.githubusercontent.com/16662357/127758991-69769870-e37b-4093-a00e-7909f77cf491.png)

**Comment by gelguy** [comment]
`wilder#cmdline_pipeline()` accepts a `sorter` option which can be used to sort the entries. Currently the order of the entries is not guaranteed, but is typically in lexical ordering.

To use a different sorting:
```vim
wilder#cmdline_pipeline({
      \ 'language': 'python',
      \ 'fuzzy': 1,
      \ 'sorter': wilder#python_difflib_sorter(),
      \ })
```
See the `sorter` option under `:h wilder#cmdline_pipeline()` for more details.

There are other sorters available, and also `fuzzy_filter`s which do sorting, e.g.
```vim
" Requires cpsm to be installed
wilder#cmdline_pipeline({
      \ 'language': 'python',
      \ 'fuzzy': 1,
      \ 'fuzzy_filter': wilder#python_cpsm_filter(),
      \ })
```

**Comment by jdhao** [comment]
Thanks for the explanation. Setting the `sorter` key for `cmdline_pipeline` solves the issue.  I think it would be more intuitive to set sorter by default, considering that the amount of documentation of this plugin is daunting for a new user to figure out the right config 😅

**Comment by gelguy** [comment]
Thanks for the feedback! I'm trying to provide more example configs/improve the existing ones so it will be easier for new users to start.
