### ISSUE TITLE
Case Insensitive / and ?

### ISSUE THREAD

**Issue by bscuron19** [gelguy/wilder.nvim#58]
Is it possible to have suggestions displayed case insensitively? Specifically when using / and ? for searching.

**Comment by gelguy** [comment]
(I'm assuming you are using Neovim with the Python remote plugin.)

If you use set the `pattern` option to `fuzzy`, you will get fuzzy completions which are smart-case.

Alternatively, you can define a custom pattern:
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline(),
      \     wilder#python_search_pipeline({
      \       'pattern': {_, x -> join(map(split(x, '\zs'), {_, c -> '[' . tolower(c) . toupper(c) . ']'}), '') . '\w*'},
      \     }),
      \   ),
      \ ])
```
A more complex function will be needed to handle special characters.

**Comment by bscuron19** [comment]
thank you!
