### ISSUE TITLE
Make auto_select optional on accept_completion

### ISSUE THREAD

**Issue by GCBallesteros** [gelguy/wilder.nvim#59]
Would it be possible to expose the `auto_select` being run on the call to `run_pipeline` in `wilder#main#accept_completion` as an option?

I personally find it (mildly) annoying that when I accept something from the list  the first value from the next list gets autocompleted because that stops me from keeping typing. Instead I have to get rid of the autocompletion then type.

My current solution is to manually set it to `0` but having the option to disable would be nice.

Edit: I can attempt a pull request if you think the request is reasonable

**Comment by gelguy** [comment]
A pull request will be great!

I would implement it by letting `wilder#main#accept_completion()` accept an optional `auto_select` argument.
