### ISSUE TITLE
vim-rails commands generate: pipeline: Vim(let):E716: Key not present in Dictionary

### ISSUE THREAD

**Issue by jdsutherland** [gelguy/wilder.nvim#60]
I noticed that commands from vim-rails generate errors:
![image](https://user-images.githubusercontent.com/5385846/127905597-325cf2f2-c689-4d28-b157-94c62fe59386.png)
I'm guessing this might be due to the fact that vim-rails loads dynamically based on files existing (IIRC, `app/` and `config/environment.rb`).

It's not a big deal as you can ignore it and continue manually triggering completions but I figured I'd flag it.

**Comment by gelguy** [comment]
Thanks for the report!

I've just pushed a fix (b8f07143ad9399adafebb902ad04d61c97dd711e). Please pull the latest master to verify!
