### ISSUE TITLE
Add hint for dein users in readme

### ISSUE THREAD

**Issue by aMOPel** [gelguy/wilder.nvim#64]
Hey there, 

really nice plugin. I just struggled for an eternity trying to figure out why it didn't work for me.

After a long time i realized that this line in my vimrc:
`let g:dein#lazy_rplugins = v:true`
means that i have to lazy load the plugin, which i didn't at first.
In fact before this plugin i had no idea what remote plugins are.

Maybe it would be a nice hint for dein users in the readme. 

Obviously it's my own stupidity, but i can imagine few people are familiar with remote plugins, since it isn't commonly used by plugins. At least i haven't seen it a lot.

Thanks for the plugin, have a nice day.

**Comment by gelguy** [comment]
Can I check the settings you use to lazy load the plugin i.e. the arguments for `dein#add('gelguy/wilder.nvim', ...)`?

I'll add a section in the README.

**Comment by aMOPel** [comment]
Basically I stole the config of Shougo.
It's unnecessarily complicated though.

sourced in init.vim:
dein.rc.vim:
```
let g:dein#auto_recache = v:true
let g:dein#lazy_rplugins = v:true
let g:dein#install_progress_type = 'title'
let g:dein#enable_notification = v:true
let g:dein#inline_vimrcs = ['options.vim', 'mappings.vim', 'unix.rc.vim', 'lsp.vim']
if has('nvim')
 call add(g:dein#inline_vimrcs, 'neovim.rc.vim')
endif
call map(g:dein#inline_vimrcs, "resolve(expand('$XDG_CONFIG_HOME/nvim/rc/' . v:val))")

let s:dein_tomls = ['dein.toml', 'deinlazy.toml', 'deinft.toml']
call map(s:dein_tomls, "resolve(expand('$XDG_CONFIG_HOME/nvim/rc/' . v:val))")

let s:path = expand('$XDG_CACHE_HOME/dein')
if !dein#load_state(s:path)
  finish
endif

set rtp^=~/.local/fzf
call dein#begin(s:path, [
      \ expand('<sfile>'), s:dein_tomls[0], s:dein_tomls[1], s:dein_tomls[2],
      \ ])

call dein#load_toml(s:dein_tomls[0], {'lazy' : 0})
call dein#load_toml(s:dein_tomls[1], {'lazy' : 1})
call dein#load_toml(s:dein_tomls[2])

call dein#end()
call dein#save_state()

if !has('vim_starting') && dein#check_install()
  " Installation check.
  call dein#install()
endif
```
deinlazy.toml:
```
[[plugins]]
repo = 'https://github.com/gelguy/wilder.nvim'
on_event = 'CmdlineEnter'
hook_post_source = '''
  call wilder#enable_cmdline_enter()
  set wildcharm=<Tab>
  cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
  cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"

  call wilder#set_option('modes', ['/', '?', ':'])
'''
```
This way it works. However when I was not lazy loading the plugin by having the config in dein.toml, it wouldn't work because of `let g:dein#lazy_rplugins = v:true`

**Comment by gelguy** [comment]
Thanks!

I've updated the README in 719e83269062b7421a4e82f3d77263915b12d452.
