### ISSUE TITLE
Wilder changes behaviour of <Up> when searching

### ISSUE THREAD

**Issue by Melkster** [gelguy/wilder.nvim#69]
Vim's default behaviour of `<Up>` in `/` breaks with wilder.

This is what `:help c_<Up>` reads:

```txt
							c_<Up> c_Up
<Up>	recall older command-line from history, whose beginning
		matches the current command-line (see below).
```

**To reproduce:**

1. Use the following minimal `.vimrc`:

```vim
call plug#begin('~/.config/nvim/packages/')
Plug 'gelguy/wilder.nvim'
call plug#end()

call wilder#enable_cmdline_enter()
```

2. Do `/` and then press `<Up>` a couple of times.
3. Some other text that is not part of your latest searches show up.
4. Compare to doing this with an empty `.vimrc`, which does what `:help c_<Up>` describes

**Expected behaviour when pressing `<Up>`:**

Your latest searches show up in the command-line.

`<Up>` does seem to work with `:` (command-line mode), but does not work with `?` (backwards search).

**Comment by gelguy** [comment]
I can reproduce this.

This is a side-effect of https://github.com/gelguy/wilder.nvim/pull/65. I missed out that the cmdline changing would affect history too.

This can be fixed by setting the `apply_incsearch_fix` option off:
```vim
call wilder#enable_cmdline_enter()

call wilder#set_option('renderer', wilder#wildmenu_renderer({'apply_incsearch_fix': 0}))
```

I'll add documentation on this and try to find a different way to fix incsearch.

**Comment by gelguy** [comment]
I've pushed a fix in the latest master: (fda3866f6b61961fbcd723ed83a61af29e272a3c). Let me know if this bug is fixed too.

Thanks for reporting!

**Comment by jdhao** [comment]
Same issue here tested on latest version of wilder.nvim.

For `/` and `?` search, `<UP>` only works once. That is, if we press `/`, then press `<UP>`, recent search item is shown. However, if you press `<UP>` after that, the search item won't switch to older search items.

`<UP>` for command mode `:`  works as expect though.

**Comment by gelguy** [comment]
Just to confirm: this isn't fixed. I don't think a workaround can be done on the VimScript side. https://github.com/neovim/neovim/pull/15380 should fix this issue.

**Comment by gelguy** [comment]
I've just updated the default `apply_incsearch_fix` option in 28b26ffa8c3a8bdc34e00bc971199d1bfba30c8f.

If you're using Nvim 0.5.1+, the option does not need to be set anymore.

Thanks for your patience everyone! I will be marking this as closed.
