### ISSUE TITLE
Vim regular expressions are not supported and cause 'bad escape' errors

### ISSUE THREAD

**Issue by Frederick888** [gelguy/wilder.nvim#71]
For example, when I search for `\chello`, it prints out a warning `python_search: bad escape \c at position 1`.

Considering behaviours of Vim regexps are sometimes influenced by settings as well, e.g. `ignorecase`, `smartcase`, I'm wondering if it's possible to leave this part of job to Vim itself? Or it's time to find/create a Vim regexp library for Python?

**Comment by gelguy** [comment]
Unfortunately I don't have plans to handle conversion of Vim's regex to PCRE.

To get suggestions from Vim's regex, you can use `wilder#vim_search_pipeline()` (Neovim by default uses `wilder#python_search_pipeline()`):
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     ... other pipelines ...
      \     wilder#vim_search_pipeline(),
      \   ),
      \ ])
```
This will provide completions for strings which start with the regex in the cmdline.

Alternatively, you can toggle which pipeline to use when special characters are detected:
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     ... other pipelines ...
      \   wilder#branch(
      \     [wilder#check({_, x -> stridx(x, '\') != -1})] + wilder#vim_search_pipeline(),
      \     wilder#python_search_pipeline(),
      \   ),
      \ ])
```

**Comment by Frederick888** [comment]
Thank you! This actually solved my use case perfectly.

Please feel free to close this issue :)
