### ISSUE TITLE
Leading lines of input() prompt are cleared

### ISSUE THREAD

**Issue by Frederick888** [gelguy/wilder.nvim#72]
I'm using neovim 0.5.0 with the following minimal rc:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

" vim-plug
call plug#begin()

Plug 'gelguy/wilder.nvim'

call plug#end()

" wilder.nvim
call wilder#enable_cmdline_enter()
call wilder#set_option('modes', ['/', '?', ':'])

function! Foo() abort
  let prompt = "hello\nworld: "
  call input(l:prompt)
endfunction
function! Bar() abort
  echo 'hello'
  echo 'world'
  call input('User input: ')
endfunction

" vim: set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab:
```

Now if I `:call Foo()`, I'd expect the following in cmdline:
```
hello
world: 
```
But instead it shows:
```
world:
```

Similarly if I `:call Bar()`, I expect
```
hello
world
User input: 
```
But instead it shows only
```
User input: 
```

If I comment out
```vim
call wilder#enable_cmdline_enter()
call wilder#set_option('modes', ['/', '?', ':'])
```
from vimrc above, the outputs are back to normal.

**Comment by gelguy** [comment]
Thanks for reporting!

I've just pushed a fix to master: f70f292f9e680b3645c8e24ebee524264a9e75e2. Could you help verify that this fixes the bug?

**Comment by Frederick888** [comment]
@gelguy Thanks a ton for the help!

However, while the original problem was solved, now if I `set cmdheight=2` then `call Foo()`, still somehow only `world:` is shown (and still commenting out the wilder.nvim configs gets the normal behaviour back). Similarly if I `set cmdheight=3` and `call Bar()`, now this also only shows the last line. So I guess it happens when cmdheight is greater or equal to number of lines of output.

**Comment by gelguy** [comment]
Thanks again for the update!

This is a Neovim bug, I've opened https://github.com/neovim/neovim/issues/15403.

**Comment by gelguy** [comment]
I've pushed another workaround: 3b1844d9d69972bec131aa66562afa545b00c883. Hopefully this resolves the issue.

**Comment by Frederick888** [comment]
@gelguy Yup I can confirm the issue is resolved! Thanks!
