### ISSUE TITLE
how to configure pseudo-transparency (winblend / pumblend) ?

### ISSUE THREAD

**Issue by jtprince** [gelguy/wilder.nvim#73]
I have basic pop-up menu pseudo-transparency set in my init.vim file:
```vim
set termguicolors
set pumblend=50
```

This gives me psuedo-transparent popup windows with coc (not shown) and telescope (telescope config shown below using `winblend`):

```
lua << EOF
require('telescope').setup{
  defaults = {
    ...
    winblend = 20,
    ...
  }
}
EOF
```

How do I configure this pumblend/winblend feature for wilder?  Can we include that in the docs? (If someone shows me how, then I could create a PR to include the instructions in the README).

**Comment by gelguy** [comment]
`winblend` is an option for `wilder#popupmenu_renderer()`.

```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'winblend': 20,
      \ ... other options ...
      \ }))
```
I'll consider inheriting the global `winblend` option by default.
