### ISSUE TITLE
[Question] I want to set pumblend to floatwin

### ISSUE THREAD

**Issue by yuki-yano** [gelguy/wilder.nvim#76]
I would like to set pumblend on the completion window to make it transparent.
I think the image in the README sets the transparency, but I couldn't figure out how to do it after reading the doc.
How can I set it to make the completion window transparent?

**Comment by gelguy** [comment]
This is a duplicate of #73.

`winblend` is an option for `wilder#popupmenu_renderer()`.

```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'winblend': 20,
      \ ... other options ...
      \ }))
```

Note: this only works for Neovim.

I'll update the doc to make it clearer about what `winblend` does.

**Comment by yuki-yano** [comment]
Thanks!
