### ISSUE TITLE
vim8 native package manager support

### ISSUE THREAD

**Issue by YevhenKap** [gelguy/wilder.nvim#77]
Hello 👋
Can this awesome plugin be installed with vim8's native package manager? If it can then what is the installation process?
Thank you)

**Comment by gelguy** [comment]
I'm not too familiar with the native package manager, but I believe there isn't anything special to be done to add this via the package manager.

1. `git clone` wilder into `~/.vim/pack/*/start` where `*` can be any directory. (or change `~/.vim` to any directory under the `&packpath` option.
2. In your `vimrc` add the line `call wilder#setup()` and the plugin should work.

**Comment by YevhenKap** [comment]
I have tried to do it, but on vim startup, it gave me an error that `wilder#setup` is not a registered function.

```
Error detected while processing /Users/username/.vimrc:
line   62:
E117: Unknown function: wilder#setup
Press ENTER or type command to continue
```

I wrote `call wilder#setup({'modes': [':', '/', '?']})` to `.vimrc`.

**Comment by gelguy** [comment]
Ah, looks like packages under `start` aren't loaded until after `.vimrc` is sourced.

Could you try adding `wilder` to `~/.vim/pack/*/opt` instead?

Then in your `.vimrc` you can add:
```vim
packadd wilder
call wilder#setup()
```

**Comment by gelguy** [comment]
Hi, any updates on this? Does adding to `~/.vim/pack/*/opt` work?

**Comment by YevhenKap** [comment]
Hi!
I sincerely apologize for my silence. Yes, it works now 😃 The only sad thing is that I cannot see popup with completions. But this is probably because I use `Vim` instead of `Neovim`.
Thank you 👍
