### ISSUE TITLE
Feature Request: wilder menu in centered floating window

### ISSUE THREAD

**Issue by yingzhu146** [gelguy/wilder.nvim#78]
First off, this is fantastic and so good it should be built in. Thanks a ton, you're a legend.

especially on large high res screens, looking down to the command bar having to move my head is a bit annoying - what I'd love is a telescope-esque UI that floats in the middle of the screen. Potentially even actually using telescope.
This would also give you a lot of extra space to do cool things like e.g. preview the file if someone is typing `:e <myfile.py>`, previewing the man page if someone is doing `! curl` etc.

I know this is probably a lot of work but nonetheless think cool idea.

Thanks a ton!

**Comment by gelguy** [comment]
Thanks for using the plugin!

I have plans to for a Telescope-like renderer on my roadmap, but don't have a specific timeframe I can say it done by.

Regarding the preview windows for extra context, I can see it being a useful feature (e.g. showing help for a command when completing it), but I don't have plans for this. The current focus is for `wilder` to be a better `wildmenu`, so the preview window is not a main goal.

**Comment by gelguy** [comment]
FYI: There's a new plugin which does this https://github.com/VonHeikemen/fine-cmdline.nvim.

**Comment by gelguy** [comment]
Thanks for your patience! I've added this feature in the #127. You can test it out by setting

```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer(wilder#popupmenu_palette_theme({
      \ 'border': 'rounded',
      \ })))
```

Here's a sample gif:
![palette4](https://user-images.githubusercontent.com/1418660/161427506-c063b4d6-6568-4329-a546-9561da434c38.gif)

**Comment by yingzhu146** [comment]
Amazing, thank you so much! Is it possible to change the font on the cmd line to the background font to effectively "hide" it?

**Comment by gelguy** [comment]
Unfortunately the cmdline uses the `Normal` highlight group so it's not possible to hide it. Neovim also doesn't support drawing floats over the cmdline either.

**Comment by yingzhu146** [comment]
totally understand :) 

Also quick one - can't figure out how to setup the devicons - this is my lua config - assume I'm understanding something wrong
```lua
local wilder = require('wilder')
wilder.setup({modes = {':', '/', '?'}})
wilder.set_option('renderer', wilder.popupmenu_renderer(
  wilder.popupmenu_palette_theme({
    highlighter = wilder.basic_highlighter(),
    left = {' ', wilder.popupmenu_devicons()},
    right = {' ', wilder.popupmenu_scrollbar()},
    border = 'rounded',
    max_height = '75%',      -- max height of the palette
    min_height = 0,          -- set to the same as 'max_height' for a fixed height window
    prompt_position = 'top', -- 'top' or 'bottom' to set the location of the prompt
    reverse = 0,             -- set to 1 to reverse the order of the list, use in combination with 'prompt_position'
  })
))
```

**Comment by yingzhu146** [comment]
@gelguy is this now possible with https://github.com/neovim/neovim/pull/16251?

**Comment by gelguy** [comment]
Unfortunately `set cmdheight=0` will still show the cmdline when entering cmdline mode (e.g. with `:`), so it is still not possible to hide the cmdline.

**Comment by yingzhu146** [comment]
thanks for the quick reply! I had hoped there was like an autocommand to hide it everytime. oh well!

**Comment by yingzhu146** [comment]
actually @gelguy 


This does pretty much all I need, incl. get rid of the cursor:

```lua
autocmd({"CmdLineLeave"},{
    callback = function()
vim.cmd[[set termguicolors]]
vim.cmd[[hi Cursor guifg=white guibg=white]]
vim.cmd[[hi Cursor2 guifg=white guibg=white]]
vim.cmd[[set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50]]
end
})
autocmd({"CmdLineEnter"},{
    callback = function()
vim.cmd[[set termguicolors]]
vim.cmd[[hi Cursor guifg=black guibg=black]]
vim.cmd[[hi Cursor2 guifg=black guibg=black]]
vim.cmd[[set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50]]
end
})
```
