### ISSUE TITLE
[Question] Popupmenu highlight group

### ISSUE THREAD

**Issue by argapost** [gelguy/wilder.nvim#81]
Hello and thanks for this plugin!

Just a quick question I want to change the color of the popup menu from the docs it seems that its highlight group is StatusLine but if I change the color of the StatusLine the popup menu stays the same.

How can I change the background color of the popup menu?

Thank you in advance for your help!

**Comment by gelguy** [comment]
Thanks for using!

The default highlight group used by `wilder#popupmenu_renderer()` is `Pmenu`. See the `highlights` option under `:h wilder#popupmenu_renderer()` for more details.

There's 2 ways you can change the highlight used:
1. Change the `Pmenu` highlight group directly (e.g. `hi! Pmenu ...`)
2. Change the `highlights.default` option passed to `wilder#popupmenu_renderer()`:
```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'highlights': {
      \   'default': '<new highlight here>',
      \ },
      \ }))
```

Option 2 is recommended as it doesn't affect other things using the `Pmenu` highlight.

**Comment by argapost** [comment]
Thank you it worked!
