### ISSUE TITLE
Cannot register wilder using `UpdateRemotePlugins`

### ISSUE THREAD

**Issue by huyiqun** [gelguy/wilder.nvim#82]
I have configured to have `wilder` when typed `:` in command mode and received this error `pipeline: Vim(call):E117: Unknown function: _wilder_python_fuzzy_filt`. By researching a little, this seems to be because that rplugin manifest is not up-to-date and I need to run `UpdateRemotePlugins`. However, when I tried to do so, I got the following message:

```
wilder: Python initialization failed
Vim(call):E117: Unknown function: _wilder_init
function remote#host#UpdateRemotePlugins[6]..<SNR>49_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[14]..provider#Poll, line 7
Vim(if):Error invoking 'poll' on channel 3 (python3-client):^@ch 3 was closed by the client
function remote#host#UpdateRemotePlugins[6]..<SNR>49_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[14]..provider#Poll, line 17
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
remote/host: generated rplugin manifest: /Users/yhu/.local/share/nvim/rplugin.vim
```
Have not idea what this means... Tried setting `g:python3_host_prog` explicitly, did not make any difference. Also tried with the `$NVIM_PYTHON_LOG_FILE` thing, but the log file returned empty.

Any help is really appreciated!

**Comment by gelguy** [comment]
The errors should mean that Neovim's Python3 environment is not set up correctly.

Could you run `:checkhealth provider` and paste the results here?

**Comment by huyiqun** [comment]
Thank you for the comment, @gelguy ! Sorry for getting back to you late.

I finally figured out that it is another python package (which also requires `UpdateRemotePlugins`) missing that causes this problem. It has nothing to do with `wilder` or the python environment. In fact, this is what the `:checkhealth provider` returned when I was having the problem:

```
## Python 3 provider (optional)
  - INFO: pyenv: Path: /Users/yhu/dotfiles/pyenv/libexec/pyenv
  - INFO: pyenv: Root: /Users/yhu/dotfiles/pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /Users/yhu/.pyenv/versions/miniconda3-latest/envs/cuda/bin/python3
  - INFO: Python version: 3.7.9
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

Sadly, there is no explicit log that tells me the error message is caused by the other python package. I just happened to install it at some point which magically solved this problem. Thanks for the help and closing.

**Comment by damiannmm** [comment]
@huyiqun, could you tell me how you solve that? I'm having this currently and don't know which pip should I install.

**Comment by damiannmm** [comment]
Turns out it was related to #109
