### ISSUE TITLE
Tabbing quickly through the history menu causes API error

### ISSUE THREAD

**Issue by akinsho** [gelguy/wilder.nvim#84]
![wilder-history](https://user-images.githubusercontent.com/22454918/133126935-4672e7ae-e4f0-4ce7-8f2c-26e170ebcfb5.gif)

Spamming the `<tab>` key with the history picker open causes an `wilder: draw: Vim(call):E5555: API call: E523: Not allowed here` error. 

My wilder config is
```vim
call wilder#enable_cmdline_enter()
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
call wilder#set_option('modes', ['/', '?', ':'])

call wilder#set_option('pipeline', [
    \ wilder#branch(
    \   [
    \     wilder#check({_, x -> empty(x)}), " probably the only Relevant Bit
    \     wilder#history(),
    \   ],
    \   wilder#python_file_finder_pipeline(#{
    \     file_command: ['rg', '--files'],
    \     filters: ['fuzzy_filter', 'difflib_sorter'],
    \   }),
    \   wilder#substitute_pipeline(#{
    \     pipeline: wilder#python_search_pipeline(#{
    \       skip_cmdtype_check: 1,
    \       pattern: wilder#python_fuzzy_pattern(#{
    \         start_at_boundary: 0,
    \       }),
    \     }),
    \   }),
    \   wilder#cmdline_pipeline(#{
    \     fuzzy: 1,
    \     sorter: wilder#python_difflib_sorter(),
    \     fuzzy_filter: wilder#lua_fzy_filter(),
    \   }),
    \   wilder#python_search_pipeline(#{
    \     pattern: 'fuzzy',
    \   }),
    \ ),
    \])

let s:highlighters = [
  \ wilder#lua_pcre2_highlighter(),
  \ wilder#lua_fzy_highlighter(),
  \]

let s:menu_accent = wilder#make_hl(
    \ 'WilderAccent',
    \ 'Normal',
    \ 'TabLineSel'
    \)

let s:wildmenu_renderer = wilder#wildmenu_renderer(#{
    \  highlighter: s:highlighters,
    \  separator: ' · ',
    \})

let s:popupmenu_renderer = wilder#popupmenu_renderer(
    \ wilder#popupmenu_border_theme(#{
    \   winblend: 3,
    \   highlights: #{
    \    default: 'Normal',
    \    border: 'NormalFloat',
    \    accent: s:menu_accent,
    \  },
    \  border: 'rounded',
    \  highlighter: s:highlighters,
    \  left: [
    \   wilder#popupmenu_devicons(),
    \   wilder#popupmenu_buffer_flags({
    \     'flags': ' a + ',
    \     'icons': {'+': '', 'a': '', 'h': ''},
    \   }),
    \  ],
    \  right: [' ', wilder#popupmenu_scrollbar()],
    \ })
    \)

call wilder#set_option('renderer', wilder#renderer_mux({
    \ ':': s:popupmenu_renderer,
    \ '/': s:wildmenu_renderer,
    \ 'substitute': s:wildmenu_renderer,
    \})
    \)
```

Please let me know if you need any more information. I'm presuming that it should be reproducible with my setup

**Comment by gelguy** [comment]
Thanks for the report! I can reproduce this.

This is due to triggering `inccommand` when tabbing to a `s/...` entry.

I'm working on a fix.

**Comment by gelguy** [comment]
I've pushed `e8a9e7e93152f9195b0d7f2d2798bbde1423c13c`. Could you check if the latest `master` fixes this issue?

**Comment by akinsho** [comment]
Just tried it out, and I'm no longer seeing the error 👍🏿 thanks. Now they aren't erroring anymore I noticed the substitute pipeline gets triggered whilst the history one is open once I tab into an old substitute command. Not sure what the right behaviour should be there, could I maybe make the history branch only insert values on a pressing enter or something 🤔 or maybe filter out all the substitution command. In either case, feel free to (or I can) close this issue since the original problem is resolved

**Comment by gelguy** [comment]
Can I confirm if the `substitute` commands are being run? Or that `wilder#wildmenu_renderer()` becomes active (but the `history` completions are showing)? If it's the latter, this is because the current cmdline is a `substitute` command and so `wilder#renderer_mux()` picks `s:wildmenu_renderer`.

To always use `s:popupmenu_renderer` when using the history pipeline:
```vim
let s:always_use_popupmenu = 0
function! s:set_always_use_popupmenu(use, x)
  let s:always_use_popupmenu = a:use
  return a:x
endfunction

call wilder#set_option('pipeline', [
    \ {_, x -> s:set_always_use_popupmenu(0, x)},
    \ wilder#branch(
    \   [
    \     wilder#check({_, x -> empty(x)}),
    \    {_, x -> s:set_always_use_popupmenu(getcmdtype() ==# ':', x)},
    \     wilder#history(),
    \   ],
    \  ... other pipelines ...
    \ ),
    \ ])

call wilder#set_option('renderer', wilder#renderer_mux([
      \ [{-> s:always_use_popupmenu}, s:popupmenu_renderer],
      \ ['substitute', s:wildmenu_renderer],
      \ [':', s:popupmenu_renderer],
      \ ['/', s:wildmenu_renderer],
      \ ]))

```

Otherwise it's possible to filter out `substitute` commands but the parsing is quite expensive performance-wise. I'll write an example filter here if you're interested.

**Comment by akinsho** [comment]
@gelguy it was the latter, i.e. the wildmenu renderer would open. Thanks, the example stops it from happening 👍🏿

**Comment by akinsho** [comment]
Actually @gelguy sorry 😅 I just noticed that the example causes the selected icon to lag by 1 e.g. if I have 
```
item  -- cursor here
s/will
s/fuzzy
```
and press `<tab>` the cursor will appear to remain on item, but `s/will` will be in the commandline the next press will then show the cursor on `s/will` but `s/fuzzy` will be on the commandline. Tbh it's not a huge issue, just wondering if there's a simple tweak I can make to the example to resolve the it.

**Comment by gelguy** [comment]
This is a known issue, caused by https://github.com/neovim/neovim/pull/9783.

`inccommand` causes `redraw` to become a no-op so `wilder` will always be 1 `redraw` behind.

Unfortunately I don't have a workaround for this - `redraw`ing in `substitute` command is generally very buggy in Neovim.
