### ISSUE TITLE
Opening the autocomplete/popup menu only when a keybind is pressed 

### ISSUE THREAD

**Issue by AmitGolden** [gelguy/wilder.nvim#86]
Hi,
I'm really digging this plugin, I always felt that was something I needed!
I'm using the advanced config from the readme, it works great but it gets a little annoying when all I want to do is to `:wq` and the big popup menu, well, pops.

Is there a to use a keybind in order to activate the popup menu?

**Comment by gelguy** [comment]
Hi, thanks for using!

You can set the `enable_cmdline_enter` option in `wilder#setup()` to `0` to disable the popupmenu from appearing automatically.
```vim
call wilder#setup({
      \ 'modes': [':', '/', '?'],
      \ 'enable_cmdline_enter': 0,
      \ })
```

The popupmenu will show only after you press `<Tab>`.

I'll update the README on this setting.

**Comment by AmitGolden** [comment]
Thanks!
