### ISSUE TITLE
File commands from subdirectory of git repo prepend ../ to file paths

### ISSUE THREAD

**Issue by heygarrett** [gelguy/wilder.nvim#88]
```fish  
❯ nvim --version
NVIM v0.6.0-dev+nightly-836-ge61ea7772
Build type: Release
LuaJIT 2.1.0-beta3
```

**Steps to reproduce**  
```fish  
mkdir wilder_test
cd wilder_test && git init
mkdir sub_dir
touch sub_dir/file.txt
cd sub_dir
nvim
:e<space>
```

**Expected behavior**  
Rendered file list would contain `file.txt`

**Actual behavior**  
Rendered file list contains `../sub_dir/file.txt`

**Comment by gelguy** [comment]
This behavior can be changed by setting the `path` option in `wilder#python_file_finder()`:

```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#python_file_finder_pipeline({
      \       'path': '',
      \       ... other options ...
      \     }),
      \     ... other pipelines ...
      \   ),
      \ ])
```
Setting it to an empty string uses the current directory. The default uses `wilder#project_root()`, which sets the path to the project's Git or Mercurial root. The option also takes a function, see `:h wilder#python_file_finder_pipeline()` for more details.

**Comment by heygarrett** [comment]
Thank you! I should have checked the docs first. 🤦‍♂️
