### ISSUE TITLE
Make window transparent?

### ISSUE THREAD

**Issue by CallumHoward** [gelguy/wilder.nvim#90]
Is there an easy way to configure the window to be transparent? Or would it be possible to have an option to enable this? Perhaps it can read the value from `vim.o.pumblend`.

**Comment by gelguy** [comment]
This is a duplicate of #73.

`winblend` is an option for `wilder#popupmenu_renderer()`.

```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'winblend': 20,
      \ ... other options ...
      \ }))
```

Note: this only works for Neovim.

**Comment by CallumHoward** [comment]
Perfect, looks so nice thanks!
