### ISSUE TITLE
Incorrect icon received from nvim-web-devicons

### ISSUE THREAD

**Issue by notpeelz** [gelguy/wilder.nvim#94]
Wilder passes the extension of the file instead of the entire file name to nvim-web-devicons, which causes some icons to not be displayed correctly.

wilder:
<img src="https://user-images.githubusercontent.com/920910/136821791-4449a7ac-7c41-4d60-b891-ff364e843e84.png" width="150" />

In my file explorer:
<img src="https://user-images.githubusercontent.com/920910/136821996-10e4a6eb-18ba-4371-a97e-751a6452a3be.png" width="100" />

https://github.com/gelguy/wilder.nvim/blob/558bf9380df27d4be2e690f5da1958d02052987a/autoload/wilder/renderer/component/popupmenu_devicons.vim#L189-L198

**Comment by gelguy** [comment]
Thanks for the report! Looks like I was using the API wrongly.

I've just pushed 52ff550ef05a0110f4decc4629e0a58b94ca97b8 which should fix this issue. Could you help verify that the latest master fixes the issue?

**Comment by notpeelz** [comment]
Yep, works fine now. Thanks!
<img src="https://user-images.githubusercontent.com/920910/136835979-bc2cfe65-ad8d-423e-8585-f1b393c27bd9.png" width="150" />
