### ISSUE TITLE
This is a small problem

### ISSUE THREAD

**Issue by denstiny** [gelguy/wilder.nvim#95]
If you can provide your highlight group

**Comment by gelguy** [comment]
Hi, I'm not exactly sure what you mean, but you can change the highlight groups used by the renderers:

```vim
call wilder#set_option('renderer', wilder#popupmenu_renderer({
      \ 'highlighter': wilder#basic_highlighter(),
      \ 'highlights': {
      \   'default': 'Search',
      \ },
      \ }))
```

The list of highlights used can be found at `:h wilder#wildmenu_renderer()` under the `highlights` option.

**Comment by denstiny** [comment]
> ![](https://gist.githubusercontent.com/gelguy/018d7fb1d5292500b2f9bc6d209a7972/raw/3be41ed723b5eb31928787ee25e5545c08a96061/border.gif)
> 
> 我按照你的文档配置了，但是还是不能满足你这个效果

How is your color

**Comment by denstiny** [comment]
> The popupmenu settings in the GIF can be set using the config below (see the https://github.com/gelguy/wilder.nvim#gradient-highlighting-experimental for setting up gradient highlighting).
> 
> ```vim
> " Change this to a color which suits your colorscheme
> let s:accent_fg = "#ea4298"
> 
> call wilder#set_option('renderer', wilder#popupmenu_renderer(wilder#popupmenu_border_theme({
>       \ 'border': 'rounded',
>       \ 'highlighter': wilder#basic_highlighter(),
>       \ 'highlights': {
>       \   'default': 'Pmenu',
>       \   'accent': wilder#make_hl('WilderAccent', 'Pmenu', [{}, {}, {'foreground': s:accent_fg}]),
>       \ },
>       \ 'left': [' ', wilder#popupmenu_devicons(), wilder#popupmenu_buffer_flags()],
>       \ 'right': [' ', wilder#popupmenu_scrollbar()],
>       \ })))
> ```

I want your Pmenu parameters.

**Comment by denstiny** [comment]
> GIF 使用`tokyonight`来自https://github.com/ghifarit53/tokyonight-vim的颜色方案。
> 
> ```
> hi Pmenu
> Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#a9b1d6 guibg=#2a2b3d
> ```
Toktonight - vim is a great configuration, it's a pity that he is not Shared
