### ISSUE TITLE
An error occurred in Ex mode

### ISSUE THREAD

**Issue by Evolution404** [gelguy/wilder.nvim#96]
After this minimize configuration, an error message appears after each command in `Ex mode`
`call wilder#setup({'modes': [':']})`
![image](https://user-images.githubusercontent.com/35091674/137238283-2c0dc58b-5bc1-4169-9ac4-c4221f81ad22.png)
In addition, exit the `Ex mode` will be slow

**Comment by gelguy** [comment]
Thanks for the bug report! I can reproduce this.

Can I check if you use `Ex mode` a lot in your workflow? If so, I'll prioritize fixing this bug. There's a Vim/Neovim issue regarding autoload-ing functions while in Ex mode.

**Comment by gelguy** [comment]
I've just pushed f7071a649e8eff744b36b055f02bbb952efc4cbb which fixes `E749` in `Ex mode`, but the error you've encountered is actually `E501`, so I'm not sure if the commit resolves your issue. Could you help verify by pulling the latest master?

Note: The issue isn't fully fixed - there is still one `E749` if `wilder` on the first command in `Ex mode` if `wilder` has not already been autoload-ed. Subsequent commands should be error-free.

**Comment by Evolution404** [comment]
There is no error message now. I think it has been working very well.
