### ISSUE TITLE
global winblend option is not respected?

### ISSUE THREAD

**Issue by jdhao** [gelguy/wilder.nvim#98]
I set `winblend` in my init.vim. But it seems that the popup win created by wilder.nvim does not respect the `winblend` value I set and use a custom value instead?

**Comment by jdhao** [comment]
> Oh, I see. Ignore me. I have set it up in my custom wilder.nvim config.

I have removed the custom-set winblend value, but it seems that wilder.nvim still can not use the global winblend value.

**Comment by jdhao** [comment]
can the global winblend value be inheritted without specifying it in wilder.nvim?

**Comment by gelguy** [comment]
I was considering inheriting the global `&pumblend` but decided against it. I personally prefer that the `wildmenu` has a different blend than completion popupmenus.

If more people feel strongly about this, I'm open to changing the default.

**Comment by wookayin** [comment]
My two cents: I think it is fine to not inherit from `&pumblend`, but more reasonable default behavior would be to inherit from `&pumblend` (**NOT** `&winblend`) as wilder's popup renderer is supposed to replace neovim's built-in popup menu. 

Anyway users should be able to specify proper alpha values as desired. I suggest we can add a more explicit documentation into the README (which we don't have at this point).

**Comment by gelguy** [comment]
Update: I've just merged #115 which uses `&pumblend` as the default blend option.

**Comment by jdhao** [comment]
Thanks for this! This issue can be closed.
